apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cellxgene
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/203403084713/clusters/cbioportal-prod/apps/cellxgene
      targetRevision: HEAD
      directory:
        recurse: true
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  revisionHistoryLimit: 3