apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cell-explorer
spec:
  project: default
  source:
    repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
    path: argocd/aws/203403084713/clusters/cbioportal-prod/apps/cell-explorer
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: cell-explorer
    server: https://kubernetes.default.svc
