apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: genome-nexus-database
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      targetRevision: 7.3.1
      chart: mongodb
      helm:
        releaseName: gn-mongo-v0dot32-useast1b
        valueFiles:
          - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/genome-nexus-database/gn_mongodb_grch37_useast1b_helm_value.yaml
    - repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      targetRevision: 7.3.1
      chart: mongodb
      helm:
        releaseName: gn-mongo-v0dot32-grch38-ensembl95
        valueFiles:
          - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/genome-nexus-database/gn_mongodb_grch38_helm_value.yaml
    - repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      targetRevision: 7.3.1
      chart: mongodb
      helm:
        releaseName: genie-gn-mongo
        valueFiles:
          - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/genome-nexus-database/genie_gn_mongodb_helm_value.yaml
    - repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      targetRevision: 7.3.1
      chart: mongodb
      helm:
       releaseName: gn-mongo-v0dot32-beta
       valueFiles:
         - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/genome-nexus-database/gn_mongodb_beta_helm_value.yaml
    - repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      targetRevision: 7.3.1
      chart: mongodb
      helm:
        releaseName: gnap-gn-mongo
        valueFiles:
          - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/genome-nexus-database/gnap_mongodb_helm_value.yaml
    - repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      targetRevision: 7.3.1
      chart: mongodb
      helm:
        releaseName: gn_vep111_mongodb
        valueFiles:
          - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/genome-nexus-database/gn_vep111_mongodb_helm_value.yaml
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/203403084713/clusters/cbioportal-prod/apps/genome-nexus-database
      targetRevision: HEAD
      directory:
        recurse: true
      ref: k8s-repo
  destination:
    namespace: genome-nexus
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
