apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/203403084713/clusters/cbioportal-prod/apps/keel
      targetRevision: HEAD
      directory:
        recurse: true
      ref: k8s
    - repoURL: https://charts.keel.sh
      targetRevision: 1.2.0
      chart: keel
      helm:
        releaseName: keel
        valueFiles:
          - $k8s/argocd/aws/203403084713/clusters/cbioportal-prod/apps/keel/values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
