apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-genie-session
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 20.8.0
    chart: redis
    helm:
      releaseName: cbioportal-redis-genie
      # Parameters list: https://artifacthub.io/packages/helm/bitnami/redis#parameters
      parameters:
        - name: global.security.allowInsecureImages
          value: "true"
        - name: image.registry
          value: docker.io
        - name: image.repository
          value: bitnamilegacy/redis
        - name: global.imagePullSecrets[0]
          value: dockerhub-creds
        - name: architecture
          value: standalone
        - name: auth.enabled
          value: "true"
        - name: auth.existingSecret
          value: cbioportal-genie-private-blue
        - name: auth.existingSecretPasswordKey
          value: REDIS_SESSION_PASSWORD
        - name: master.persistence.enabled
          value: "false"
        - name: replica.persistence.enabled
          value: "false"
        - name: master.extraFlags[0]
          value: --maxmemory 8gb
        - name: master.extraFlags[1]
          value: --maxmemory-policy volatile-ttl
        - name: master.tolerations[0].key
          value: workload
        - name: master.tolerations[0].value
          value: cbioportal-redis
        - name: master.tolerations[0].operator
          value: Equal
        - name: master.tolerations[0].effect
          value: NoSchedule
        # This is a hack to override default params and enable FLUSHDB and FLUSHALL commands
        - name: master.disableCommands[0]
          value: CONFIG
        - name: master.disableCommands[1]
          value: SHUTDOWN
        - name: replica.disableCommands[0]
          value: CONFIG
        - name: replica.disableCommands[1]
          value: SHUTDOWN
  destination:
    namespace: default
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-genie-persistence-cache
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 20.8.0
    chart: redis
    helm:
      releaseName: cbioportal-genie-persistence-redis
      # Parameters list: https://artifacthub.io/packages/helm/bitnami/redis#parameters
      parameters:
        - name: global.security.allowInsecureImages
          value: "true"
        - name: image.registry
          value: docker.io
        - name: image.repository
          value: bitnamilegacy/redis
        - name: global.imagePullSecrets[0]
          value: dockerhub-creds
        - name: architecture
          value: replication
        - name: auth.enabled
          value: "true"
        - name: auth.existingSecret
          value: cbioportal-genie-private-blue
        - name: auth.existingSecretPasswordKey
          value: REDIS_PERSISTENCE_PASSWORD
        - name: master.persistence.enabled
          value: "false"
        - name: replica.persistence.enabled
          value: "false"
        - name: master.extraFlags[0]
          value: --maxmemory 8gb
        - name: master.extraFlags[1]
          value: --maxmemory-policy volatile-ttl
        - name: master.nodeSelector.workload
          value: redis
        - name: master.tolerations[0].key
          value: workload
        - name: master.tolerations[0].value
          value: cbioportal-redis
        - name: master.tolerations[0].operator
          value: Equal
        - name: master.tolerations[0].effect
          value: NoSchedule
        - name: master.resources.limits.memory
          value: 10Gi
        - name: master.resources.limits.cpu
          value: 150m
        - name: master.resources.requests.memory
          value: 8Gi
        - name: master.resources.requests.cpu
          value: 100m
        - name: replica.replicaCount
          value: "2"
        - name: replica.autoscaling.enabled
          value: "true"
        - name: replica.autoscaling.minReplicas
          value: "2"
        - name: replica.autoScaling.maxReplicas
          value: "3"
        - name: replica.extraFlags[0]
          value: --maxmemory 8gb
        - name: replica.extraFlags[1]
          value: --maxmemory-policy volatile-ttl
        - name: replica.nodeSelector.workload
          value: redis
        - name: replica.tolerations[0].key
          value: workload
        - name: replica.tolerations[0].value
          value: cbioportal-redis
        - name: replica.tolerations[0].operator
          value: Equal
        - name: replica.tolerations[0].effect
          value: NoSchedule
        - name: master.disableCommands[0]
          value: CONFIG
        - name: master.disableCommands[1]
          value: SHUTDOWN
        - name: replica.disableCommands[0]
          value: CONFIG
        - name: replica.disableCommands[1]
          value: SHUTDOWN
        - name: replica.resources.limits.memory
          value: 6Gi
        - name: replica.resources.limits.cpu
          value: 150m
        - name: replica.resources.requests.memory
          value: 4Gi
        - name: replica.resources.requests.cpu
          value: 100m
  destination:
    namespace: default
    server: https://kubernetes.default.svc
