apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: cbioportal
    run: cbioportal-backend-public-beta-offline
  name: cbioportal-backend-public-beta-offline
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cbioportal-backend-public-beta-offline
  template:
    metadata:
      labels:
        run: cbioportal-backend-public-beta-offline
    spec:
      containers:
        - name: cbioportal-backend-public-beta-offline
          image: cbioportal/cbioportal:public-beta-portal-offline-2025-10-13
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      nodeSelector:
        workload: "cbio-dev"
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "cbio-dev"
          effect: "NoSchedule"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: cbioportal
    run: cbioportal-backend-public-beta-offline
  name: cbioportal-backend-public-beta-offline
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    run: cbioportal-backend-public-beta-offline
  type: ClusterIP
