apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-19T15:46:42Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genie-genome-nexus
spec:
  image: ami-033814661676c4595
  machineType: t2.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: genie-genome-nexus
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-09T21:11:58Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genie-portals
spec:
  image: ami-020b8ffb1f0f566bd
  machineType: r5.xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: genie-portals
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-19T14:49:29Z"
  generation: 14
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genome-nexus
spec:
  image: ami-00df8fdd204d6985d
  machineType: t3.xlarge
  maxSize: 5
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: genome-nexus
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-15T20:00:57Z"
  generation: 7
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: gnap-genome-nexus
spec:
  image: ami-033814661676c4595
  machineType: t3.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: gnap-genome-nexus
  role: Node
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-10-24T21:18:37Z"
  generation: 26
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: large-mem
spec:
  image: ami-03b850a018c8cd25e
  machineType: r5.xlarge
  maxSize: 5
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: large-mem
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-08-06T18:29:31Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: master-us-east-1a
spec:
  image: ami-0335054bb7a81bf6f
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-03-30T21:50:55Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: mission-critical
spec:
  image: ami-03b850a018c8cd25e
  machineType: r5.xlarge
  maxSize: 3
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: mission-critical
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c
  taints:
  - dedicated=mission-critical:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-08-06T18:29:31Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: nodes
spec:
  image: ami-03b850a018c8cd25e
  machineType: t2.medium
  maxSize: 5
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-03-16T17:36:46Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: oncokb
spec:
  image: ami-03b850a018c8cd25e
  machineType: r5.2xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: oncokb
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c
  taints:
  - dedicated=oncokb:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-02T20:34:53Z"
  generation: 5
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: redis-persistence-cache
spec:
  image: ami-033814661676c4595
  machineType: r5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: redis-persistence-cache
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c
