kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homo-sapiens-core-pv
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: eks.amazonaws.com/nodegroup
              operator: In
              values: # Important that this goes on node with enough local storage
                - eks-genome-nexus-vep
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    run: gn-vep-2
  name: homo-sapiens-core-pv-claim
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-storage
apiVersion: v1