image:
  repository: genomenexus/gn-mongo
  tag: 0.31_mutationassessor
persistence:
  size: 150Gi
nodeSelector:
  eks.amazonaws.com/nodegroup: eks-oncokb-load-testing
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "eks-oncokb-load-testing"
    effect: "NoSchedule"
