redis:
  configmap: |-
    maxmemory 1Gb
    maxmemory-policy allkeys-lru
  livenessProbe:
    initialDelaySeconds: 60
    failureThreshold: 10
    timeoutSeconds: 5
  readinessProbe:
    failureThreshold: 10
    timeoutSeconds: 5
  nodeSelector:
    eks.amazonaws.com/nodegroup: eks-oncokb-load-testing
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "eks-oncokb-load-testing"
    effect: "NoSchedule"

cluster:
  # To successfully set the cluster up, it will need to have at least 3 master nodes. 
  # The total number of nodes is calculated like: nodes = numOfMasterNodes + numOfMasterNodes * replicas. 
  # Hence, the defaults cluster.nodes = 6 and cluster.replicas = 1 means, 3 master and 3 replica nodes will be deployed by the chart.
  nodes: 20     # 10 master nodes  + 10 master nodes * 1 replicas = 20 nodes
  replicas: 1