image:
  repository: genomenexus/gn-mongo
  tag: 0.32_grch38_ensembl95
  pullPolicy: Always
persistence:
  enabled: true
  size: 200Gi

# If want to deploy the MongoDB pods on a specific node, uncomment the following lines
# affinity:
# nodeAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#       - matchExpressions:
#           - key: kubernetes.io/hostname
#             operator: In
#             values:
#               -  # Replace with the exact node name

tolerations:
  - key: workload
    operator: Equal
    value: gn-database
    effect: NoSchedule

nodeSelector:
  workload: gn-database
  # kubernetes.io/hostname: # Replace with the exact node name
resources:
  requests:
    memory: 12Gi
    cpu: 2
    ephemeral-storage: 2Gi
  limits:
    memory: 20Gi
    cpu: 3
    ephemeral-storage: 4Gi