apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gn-mongo-beta-data
  namespace: genome-nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: gp2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gn-mongo-beta
  namespace: genome-nexus
  labels:
    app: gn-mongo-beta
spec:
  serviceName: gn-mongo-beta
  replicas: 1
  selector:
    matchLabels:
      app: gn-mongo-beta
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gn-mongo-beta
    spec:
      containers:
        - name: mongodb
          image: genomenexus/gn-mongo:0.32_slim_mongodb_7.0.28_rc1
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          env:
            - name: COLLECTION_UPDATE_LIST
              value: "hotspot.mutation,signal.mutation"
            - name: MONGO_DB
              value: "annotator"
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gn-mongo-beta-data
      tolerations:
        - key: workload
          operator: Equal
          value: gn-database
          effect: NoSchedule
      nodeSelector:
        workload: gn-database
---
apiVersion: v1
kind: Service
metadata:
  name: gn-mongo-beta
  namespace: genome-nexus
  labels:
    app: gn-mongo-beta
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    app: gn-mongo-beta
