image:
  repository: genomenexus/gn-mongo
  tag: 0.32_mutationassessor
  pullPolicy: Always
persistence:
  enabled: true
  size: 150Gi

# If want to deploy the MongoDB pods on a specific node, uncomment the following lines
# affinity:
# nodeAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#       - matchExpressions:
#           - key: kubernetes.io/hostname
#             operator: In
#             values:
#               -  # Replace with the exact node name

tolerations:
  - key: workload
    operator: Equal
    value: gn-database
    effect: NoSchedule

nodeSelector:
  workload: gn-database
  # kubernetes.io/hostname: # Replace with the exact node name

resources:
  requests:
    memory: 10Gi
    cpu: 2
  limits:
    memory: 18Gi
    cpu: 3