image:
  repository: genomenexus/gn-mongo
  tag: sha-6ce3181e7924f45971005d6aba1c4483a75b5f59-grch37_ensembl92-ma_true
  pullPolicy: Always
persistence:
  enabled: true
  size: 150Gi

updateStrategy:
  type: Recreate   # ensures old pods are deleted before new ones are created

# If want to deploy the MongoDB pods on a specific node, uncomment the following lines
# affinity:
# nodeAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#       - matchExpressions:
#           - key: kubernetes.io/hostname
#             operator: In
#             values:
#               -  # Replace with the exact node name

# env used by import_mongo.sh
extraEnvVars:
  - name: COLLECTION_UPDATE_LIST
    # Example: force-update these even if they already exist
    value: "hotspot.mutation,signal.mutation"
  # Optional: make the DB explicit so shell checks don’t need to parse URI
  - name: MONGO_DB
    value: "annotator"

tolerations:
  - key: workload
    operator: Equal
    value: gn-database
    effect: NoSchedule

nodeSelector:
  workload: gn-database
  # kubernetes.io/hostname: # Replace with the exact node name
