apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-cert-secret
  dnsNames:
    - "argocd.oncokb.org"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oncokb-cert
  namespace: default
spec:
  secretName: oncokb-cert-secret
  dnsNames:
    - "sop2.oncokb.org"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
