apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-cert-secret
  dnsNames:
    - "argocd.oncokb.org"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oncokb-cert
  namespace: default
spec:
  secretName: oncokb-cert-secret
  dnsNames:
    - "demo.oncokb.org"
    - "public.api.oncokb.org"
    - "sop.oncokb.org"
    - "curation.oncokb.org"
    - "keycloak.oncokb.org"
    - "staging.oncokb.org"
    - "www.oncokb.org"
    - "transcript.oncokb.org"
    - "airflow.oncokb.org"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oncokb-beta-cert
  namespace: default
spec:
  secretName: oncokb-beta-cert-secret
  dnsNames:
    - "beta.oncokb.org"
    - "beta.transcript.oncokb.org"
    - "beta.curation.oncokb.org"
    - "beta.report.oncokb.org"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
