apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-operator
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/666628074417/clusters/cbioportal-prod/apps/datadog
      targetRevision: HEAD
      directory:
        recurse: true
      ref: k8s-repo
    - repoURL: https://helm.datadoghq.com
      targetRevision: 3.109.2
      chart: datadog
      helm:
        releaseName: datadog
        valueFiles:
          - $k8s-repo/argocd/aws/666628074417/clusters/cbioportal-prod/apps/datadog/values.yaml
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
