apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/666628074417/clusters/cbioportal-prod/apps/grafana
      targetRevision: HEAD
      directory:
        recurse: true
      ref: k8s-repo
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 10.1.0
      chart: grafana
      helm:
        releaseName: grafana
        valueFiles:
          - $k8s-repo/argocd/aws/666628074417/clusters/cbioportal-prod/apps/grafana/values.yaml
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
