apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/666628074417/clusters/cbioportal-prod/apps/prometheus
      targetRevision: HEAD
      directory:
        recurse: true
      ref: k8s-repo
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 27.40.0
      chart: prometheus
      helm:
        releaseName: prometheus
        valueFiles:
          - $k8s-repo/argocd/aws/666628074417/clusters/cbioportal-prod/apps/prometheus/values.yaml
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
