apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: oncokb-core-demo
  name: oncokb-core-demo
  namespace: oncokb
  selfLink: /apis/extensions/v1beta1/namespaces/oncokb/deployments/oncokb-core-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      run: oncokb-core-demo
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: oncokb-core-demo
    spec:
      containers:
        - env:
          envFrom:
            - configMapRef:
                name: oncokb-core-demo
            - configMapRef:
                name: oncokb-db-public-rds-oncokb-user
          image: oncokb/oncokb:3.18.2-no-frontend
          command: ["java"]
          args: [
            # from https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
            "-Xms250m",
            "-XX:+UseSerialGC",
            # aggressive garbage collection
            "-XX:MinHeapFreeRatio=20",
            "-XX:MaxHeapFreeRatio=40",
            "-XX:GCTimeRatio=4",
            "-XX:AdaptiveSizePolicyWeight=90",
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+UseCGroupMemoryLimitForHeap",
            # use maxRAMFraction > 1 https://github.com/akka/akka/issues/23499
            "-XX:MaxRAMFraction=2",
            "-XX:+PrintFlagsFinal",
            "-XshowSettings:vm",
            # need to set MaxRAM, somehow the MaxRAMFraction is not picked up
            # from the limits
            "-XX:MaxRAM=1024m",
            "-Djdbc.driverClassName=com.mysql.jdbc.Driver",
            "-Djdbc.url=$(DB_URL)/oncokb_core_demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false",
            "-Djdbc.username=$(DB_USERNAME)",
            "-Djdbc.password=$(DB_PASSWORD)",
            "-Dgenomenexus.api=https://www.genomenexus.org/",
            "-Dshow_sitemaps=false",
            "-Dswagger_description=This website is for demonstration purpose. Only information of BRAF, TP53 and ROS1 are available.",
            "-Dswagger_url=https://demo.oncokb.org",
            "-Dsentry.stacktrace.app.packages=org.mskcc.cbio.oncokb,org.genome_nexus",
            "-Dsentry.sample.rate=0.1",
            "-jar",
            "/webapp-runner.jar",
            "--enable-compression",
            "--port",
            "8888",
            "/app.war"
          ]
          imagePullPolicy: Always
          # use actionable variants endpoint to cache everything
          readinessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            # wait for the pod is ready
            initialDelaySeconds: 360
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          name: oncokb-core-demo
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-oncokb"
          effect: "NoSchedule"
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-oncokb
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: oncokb-core-demo
  name: oncokb-core-demo
  namespace: oncokb
  selfLink: /api/v1/namespaces/oncokb/services/oncokb-core-demo
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    run: oncokb-core-demo
  type: ClusterIP
