apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncokb-public
  namespace: oncokb
spec:
  replicas: 5
  selector:
    matchLabels:
      app: oncokb-public
      version: 'v1'
  strategy:
    # We want to do a rolling updates to make sure all old instances removed before last new pod is initialized.
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oncokb-public
        version: 'v1'
    spec:
      containers:
        - name: oncokb-public
          image: oncokb/oncokb-public:3.16.0
          env:
            # Database schema update takes a lot of especially when changing a table with a lot of table
            # We should disable the liveness prob to avoid the pod to be terminated before the liquibase finish all the work
            - name: SPRING_PROFILES_ACTIVE
              value: prod,no-liquibase
            - name: JAVA_OPTS
              value: '-Xmx1024m -Xms512m'
            - name: APPLICATION_API_PROXY_GERMLINE_URL
              value: "http://oncokb-core-germline:8888"
            - name: APPLICATION_SAMLAWS_SERVICEACCOUNTUSERNAME
              value: '$(SERVICE_ACCOUNT_USERNAME)'
            - name: APPLICATION_SAMLAWS_SERVICEACCOUNTPASSWORD
              value: '$(SERVICE_ACCOUNT_PASSWORD)'
            - name: APPLICATION_SAMLAWS_PRINCIPALARN
              value: '$(PRINCIPAL_ARN)'
            - name: APPLICATION_SAMLAWS_ROLEARN
              value: '$(ROLE_ARN)'
            - name: APPLICATION_GITHUB_TOKEN
              value: '$(ONCOKBDEV_PUBLIC_ACCESS_TOKEN)'
            - name: APPLICATION_DB_READ_ONLY
              value: "false"
            - name: APPLICATION_REDIS_TYPE
              value: '$(REDIS_TYPE)'
            - name: APPLICATION_REDIS_ADDRESS
              value: '$(REDIS_ADDRESS)'
            - name: APPLICATION_REDIS_PASSWORD
              value: '$(REDIS_PASSWROD)'
            - name: APPLICATION_REDIS_EXPIRATION
              value: '$(REDIS_EXPIRATION)'
            - name: SENTRY_EXCEPTION_RESOLVER_ORDER
              value: '-2147483647'
            - name: SENTRY_TRACES_SAMPLE_RATE
              value: '.2'
            - name: SPRING_DATASOURCE_URL
              value: '${DB_URL}/oncokb_public'
            - name: SPRING_DATASOURCE_USERNAME
              value: '${DB_USERNAME}'
            - name: SPRING_DATASOURCE_PASSWORD
              value: '${DB_PASSWORD}'
          envFrom:
            - configMapRef:
                name: oncokb-public
            - configMapRef:
                name: oncokb-schultz-lab-sa
            - configMapRef:
                name: oncokb-github
            - configMapRef:
                name: oncokb-redis-cluster-ng
            - configMapRef:
                name: oncokb-db-public-rds-oncokb-public
          readinessProbe:
            httpGet:
              path: /
              port: 9095
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 9095
            initialDelaySeconds: 90
            timeoutSeconds: 15
            periodSeconds: 15
            failureThreshold: 10
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 2000m
          ports:
            - name: http
              containerPort: 9095
          volumeMounts:
            # The subPath is needed so that mounting the secret as a single file doesn't override
            # the contents of the existing directory.
            - mountPath: /app/resources/config/recaptcha/oncokb-recaptcha-credentials.json
              subPath: oncokb-recaptcha-credentials.json
              name: recaptcha-credentials
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-oncokb"
          effect: "NoSchedule"
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-oncokb
      volumes:
        - name: recaptcha-credentials
          secret:
            secretName: oncokb-recaptcha-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: oncokb-public
  namespace: oncokb
  labels:
    app: oncokb-public
spec:
  selector:
    app: oncokb-public
  type: ClusterIP
  ports:
    - name: http
      port: 9095
