apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncokb-public-beta
  namespace: oncokb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oncokb-public-beta
      version: "v1"
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oncokb-public-beta
        version: "v1"
    spec:
      containers:
        - name: oncokb-public-beta
          image: oncokb/oncokb-public:3.18.6
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod,no-liquibase
            - name: APPLICATION_API_PROXY_GERMLINE_URL
              value: "http://oncokb-core-germline:8888"
            - name: APPLICATION_REDIS_TYPE
              value: "$(REDIS_TYPE)"
            - name: APPLICATION_REDIS_ADDRESS
              value: "$(REDIS_ADDRESS)"
            - name: APPLICATION_REDIS_PASSWORD
              value: "$(REDIS_PASSWROD)"
            - name: APPLICATION_REDIS_EXPIRATION
              value: "$(REDIS_EXPIRATION)"
            - name: APPLICATION_DB_READ_ONLY
              value: "false"
            - name: APPLICATION_SAMLAWS_SERVICEACCOUNTUSERNAME
              value: "$(SERVICE_ACCOUNT_USERNAME)"
            - name: APPLICATION_SAMLAWS_SERVICEACCOUNTPASSWORD
              value: "$(SERVICE_ACCOUNT_PASSWORD)"
            - name: APPLICATION_SAMLAWS_PRINCIPALARN
              value: "$(PRINCIPAL_ARN)"
            - name: APPLICATION_SAMLAWS_ROLEARN
              value: "$(ROLE_ARN)"
            - name: JAVA_OPTS
              value: "-Xmx1024m -Xms512m"
            - name: SENTRY_EXCEPTION_RESOLVER_ORDER
              value: "-2147483647"
            - name: SENTRY_TRACES_SAMPLE_RATE
              value: ".2"
            - name: SPRING_DATASOURCE_URL
              value: "${DB_URL}/oncokb_public_beta"
            - name: SPRING_DATASOURCE_USERNAME
              value: "${DB_USERNAME}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "${DB_PASSWORD}"
          envFrom:
            - configMapRef:
                name: oncokb-public-beta
            - configMapRef:
                name: oncokb-schultz-lab-sa
            - configMapRef:
                name: oncokb-redis-cluster-ng
            - configMapRef:
                name: oncokb-db-public-rds-oncokb-public
          readinessProbe:
            httpGet:
              path: /
              port: 9095
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 9095
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 750m
          ports:
            - name: http
              containerPort: 9095
          volumeMounts:
            # The subPath is needed so that mounting the secret as a single file doesn't override
            # the contents of the existing directory.
            - mountPath: /app/resources/config/recaptcha/oncokb-recaptcha-credentials.json
              subPath: oncokb-recaptcha-credentials.json
              name: recaptcha-credentials
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-oncokb"
          effect: "NoSchedule"
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-oncokb
      volumes:
        - name: recaptcha-credentials
          secret:
            secretName: oncokb-recaptcha-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: oncokb-public-beta
  namespace: oncokb
  labels:
    app: oncokb-public-beta
spec:
  selector:
    app: oncokb-public-beta
  type: ClusterIP
  ports:
    - name: http
      port: 9095
