apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  labels:
    run: oncokb-core-beta
  name: oncokb-core-beta
  namespace: oncokb
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oncokb-core-beta
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: oncokb-core-beta
    spec:
      containers:
        - env:
          envFrom:
            - configMapRef:
                name: oncokb-core-beta
            - configMapRef:
                name: oncokb-redis-cluster-ng
            - configMapRef:
                name: oncokb-db-public-rds-oncokb-user
          # The beta current is used to showcase a new search endpoint
          image: oncokb/oncokb:3.29.1
          command: ["java"]
          args:
            [
              "-Dapp.name=$(APP_NAME)",
              "-Djdbc.driverClassName=com.mysql.jdbc.Driver",
              "-Djdbc.url=$(DB_URL)/oncokb_core_beta?useUnicode=yes&characterEncoding=UTF-8&useSSL=false",
              "-Djdbc.username=$(DB_USERNAME)",
              "-Djdbc.password=$(DB_PASSWORD)",
              "-Dgenomenexus.api=https://www.genomenexus.org/",
              "-Doncokb_data.access_token=$(ONCOKBDEV_PRIVATE_ACCESS_TOKEN)",
              "-Doncokb_transcript.url=https://beta.transcript.oncokb.org",
              "-Doncokb_transcript.token=$(ONCOKB_TRANSCRIPT_TOKEN)",
              "-Dredis.enable=true",
              "-Dredis.type=$(REDIS_TYPE)",
              "-Dredis.address=$(REDIS_ADDRESS)",
              "-Dredis.password=$(REDIS_PASSWROD)",
              "-Dredis.expiration=$(REDIS_EXPIRATION)",
              "-Dswagger_url=https://beta.oncokb.org",
              "-Dshow_sitemaps=false",
              "-Dsentry.stacktrace.app.packages=org.mskcc.cbio.oncokb",
              "-Dsentry.sample.rate=1",
              "-jar",
              "/webapp-runner.jar",
              "--enable-compression",
              "--port",
              "8888",
              "/app.war",
            ]
          imagePullPolicy: Always
          # use actionable variants endpoint to cache everything
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 8888
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 20
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 8888
            # wait for the pod is ready
            initialDelaySeconds: 480
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 100
          name: oncokb-core-beta
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-oncokb"
          effect: "NoSchedule"
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-oncokb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: oncokb-core-beta
  name: oncokb-core-beta
  namespace: oncokb
spec:
  ports:
    - port: 8888
  selector:
    run: oncokb-core-beta
  type: ClusterIP
