 kind: PersistentVolumeClaim
 apiVersion: v1
 metadata:
   name: oncotree-pvc
 spec:
   storageClassName: "ebs-sc"
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 30Mi 
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
parameters:
  encrypted: "true"
  type: gp2
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer