architecture: standalone
auth:
  existingSecret: cbioagent-mongodb-creds
  usernames:
    - "cbioagent"
  databases:
    - "cBioAgent"
persistence:
  enabled: true
  size: 500Gi
  resourcePolicy: keep
image:
  repository: bitnamilegacy/mongodb
  registry: docker.io
tolerations:
  - key: workload
    operator: Equal
    value: cbioagent-db
    effect: NoSchedule
nodeSelector:
  workload: cbioagent-db
sidecars:
  - name: librechat-exporter
    image: ghcr.io/virtuos/librechat_exporter:2.0.3
    imagePullPolicy: Always
    ports:
      - name: metrics
        containerPort: 8000
    env:
      - name: MONGODB_URI
        value: "mongodb://localhost:27017/"
      - name: LOGGING_LEVEL
        value: "info"
service:
  extraPorts:
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP