apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-airflow-postgresql
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  volumeName: postgresql-pv
  resources:
    requests:
      storage: 8Gi