apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databricks-s3-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: databricks-s3-pv
