apiVersion: v1
kind: PersistentVolume
metadata:
  name: hackathon-databricks-s3-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - allow-delete
    - region us-east-1
  claimRef:
    namespace: airflow
    name: hackathon-databricks-s3-pvc
  csi:
    driver: s3.csi.aws.com
    volumeHandle: hackathon-databricks-s3-volume
    volumeAttributes:
      bucketName: 'hackathon-databricks'
