apiVersion: v1
kind: PersistentVolume
metadata:
  name: databricks-s3-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - read-only
    - region us-east-1
  claimRef:
    namespace: airflow
    name: databricks-s3-pvc
  csi:
    driver: s3.csi.aws.com
    volumeHandle: databricks-s3-sc-203403084713-pp-4rxlzd426npxu-bucket-kswubqqre3jr
    volumeAttributes:
      bucketName: 'sc-203403084713-pp-4rxlzd426npxu-bucket-kswubqqre3jr'
