apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hackathon-databricks-s3-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: hackathon-databricks-s3-pv
