cluster:
  nodes: 20
  replicas: 1

image:
  registry: docker.io
  repository: bitnamilegacy/redis-cluster
global:
  security:
    allowInsecureImages: true
  imagePullSecrets:
    - oncokb-dockerhub-creds

existingSecret: redis-cluster
existingSecretPasswordKey: REDIS_PASSWORD

# We cannot use EFS because high latency hurts AOF/RDB persistence when the cache size grows
persistence:
  storageClass: gp2

redis:
  configmap: |-
    maxmemory 1Gb
    maxmemory-policy allkeys-lru
  livenessProbe:
    failureThreshold: 10
    initialDelaySeconds: 60
    timeoutSeconds: 5
  nodeSelector:
    workload: redis-cl
  readinessProbe:
    failureThreshold: 10
    timeoutSeconds: 5
  resources:
    requests:
      cpu: 100m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 3Gi
  tolerations:
    - effect: NoSchedule
      key: workload
      operator: Equal
      value: redis-cl
