apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: oncokb-core
  name: oncokb-core
spec:
  replicas: 3
  selector:
    matchLabels:
      run: oncokb-core
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: oncokb-core
    spec:
      volumes:
        - name: log4j-properties
          configMap:
            name: oncokb-core-log4j-properties
      containers:
        - env:
          envFrom:
            - secretRef:
                name: oncokb-core
            - secretRef:
                name: oncokb-db-msk-prod-rds
            - secretRef:
                name: oncokb-redis-cluster
          image: mskcc/oncokb:5.0.0
          volumeMounts:
            - mountPath: /config/
              name: log4j-properties
          command: ["java"]
          args:
            [
              "-Dapp.name=$(APP_NAME)",
              "-Djdbc.driverClassName=com.mysql.jdbc.Driver",
              "-Djdbc.url=jdbc:mysql://$(DB_HOST):$(DB_PORT)/oncokb_core_v6_2?useUnicode=yes&characterEncoding=UTF-8&useSSL=false",
              "-Djdbc.username=$(DB_USERNAME)",
              "-Djdbc.password=$(DB_PASSWORD)",
              "-Doncokb_data.access_token=$(ONCOKBDEV_PRIVATE_ACCESS_TOKEN)",
              "-Doncokb_transcript.token=$(ONCOKB_TRANSCRIPT_TOKEN)",
              "-Dredis.enable=true",
              "-Dredis.type=$(REDIS_TYPE)",
              "-Dredis.address=$(REDIS_ADDRESS)",
              "-Dredis.password=$(REDIS_PASSWORD)",
              "-Dredis.expiration=$(REDIS_EXPIRATION)",
              "-Dshow_sitemaps=false",
              "-Dsentry.stacktrace.app.packages=org.mskcc.cbio.oncokb",
              "-Dsentry.sample.rate=1",
              "-Dlog4j.configuration=file:/config/log4j.properties",
              "-jar",
              "/webapp-runner.jar",
              "--enable-compression",
              "--port",
              "8888",
              "/app.war",
            ]
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 8888
            initialDelaySeconds: 15
            timeoutSeconds: 60
            periodSeconds: 30
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 8888
            initialDelaySeconds: 600
            timeoutSeconds: 60
            periodSeconds: 10
            failureThreshold: 72
          name: oncokb-core
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        workload: lg-general
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: oncokb-core
  name: oncokb-core
spec:
  ports:
    - port: 8888
  selector:
    run: oncokb-core
  type: ClusterIP
