apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: oncokb-core-pub-data-2017
  name: oncokb-core-pub-data-2017
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oncokb-core-pub-data-2017
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: oncokb-core-pub-data-2017
    spec:
      containers:
        - env:
          envFrom:
            - secretRef:
                name: oncokb-core-pub-data-2017
            - secretRef:
                name: oncokb-db-msk-prod-rds
            - secretRef:
                name: oncokb-redis-cluster
          image: oncokb/oncokb:pub-data-2017.alpha.0
          command: ["java"]
          args: [
            "-Dapp.name=$(APP_NAME)",
            "-Djdbc.driverClassName=com.mysql.jdbc.Driver",
            "-Djdbc.url=jdbc:mysql://$(DB_HOST):$(DB_PORT)/oncokb_core_pub_data_2017?useUnicode=yes&characterEncoding=UTF-8&useSSL=false",
            "-Djdbc.username=$(DB_USERNAME)",
            "-Djdbc.password=$(DB_PASSWORD)",
            "-Doncokb_transcript.token=$(ONCOKB_TRANSCRIPT_TOKEN)",
            "-Dredis.enable=false",
            "-Dshow_sitemaps=false",
            "-Dsentry.stacktrace.app.packages=org.mskcc.cbio.oncokb",
            "-Dsentry.sample.rate=1",
            "-jar",
            "/webapp-runner.jar",
            "--enable-compression",
            "--port",
            "8888",
            "/app.war"
          ]
          imagePullPolicy: Always
          # use actionable variants endpoint to cache everything
          readinessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 20
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            # wait for the pod is ready
            initialDelaySeconds: 300
            timeoutSeconds: 5
            periodSeconds: 20
            failureThreshold: 60
          name: oncokb-core-pub-data-2017
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        workload: legacy-apps
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "legacy-apps"
        effect: "NoSchedule"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: oncokb-core-pub-data-2017
  name: oncokb-core-pub-data-2017
spec:
  ports:
    - port: 8888
  selector:
    run: oncokb-core-pub-data-2017
  type: ClusterIP
