apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: oncokb-core-germline-v2
  name: oncokb-core-germline-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oncokb-core-germline-v2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: oncokb-core-germline-v2
    spec:
      imagePullSecrets:
        - name: oncokb-dockerhub-creds
      volumes:
        - name: log4j-properties
          configMap:
            name: oncokb-core-log4j-properties
      containers:
        - env:
          envFrom:
            - secretRef:
                name: oncokb-core-germline-v2
            - secretRef:
                name: oncokb-db-msk-prod-rds
            - secretRef:
                name: oncokb-redis-cluster
          image: oncokb/oncokb:4.0.0-germline.10
          volumeMounts:
            - mountPath: /config/
              name: log4j-properties
          command: ["java"]
          args:
            [
              "-Dapp.name=$(APP_NAME)",
              "-Djdbc.driverClassName=com.mysql.jdbc.Driver",
              "-Djdbc.url=jdbc:mysql://$(DB_HOST):$(DB_PORT)/oncokb_core_germline_v2?useUnicode=yes&characterEncoding=UTF-8&useSSL=false",
              "-Djdbc.username=$(DB_USERNAME)",
              "-Djdbc.password=$(DB_PASSWORD)",
              "-Dgenomenexus.api=https://www.genomenexus.org/",
              "-Doncokb_transcript.token=$(ONCOKB_TRANSCRIPT_TOKEN)",
              "-Dredis.enable=false",
              "-Dredis.type=$(REDIS_TYPE)",
              "-Dredis.address=$(REDIS_ADDRESS)",
              "-Dredis.password=$(REDIS_PASSWROD)",
              "-Dredis.masterName=$(REDIS_MASTERNAME)",
              "-Dredis.expiration=$(REDIS_EXPIRATION)",
              "-Dshow_sitemaps=false",
              "-Dlog4j.configuration=file:/config/log4j.properties",
              "-jar",
              "/webapp-runner.jar",
              "--enable-compression",
              "--port",
              "8888",
              "/app.war",
            ]
          imagePullPolicy: Always
          # use actionable variants endpoint to cache everything
          readinessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 20
            failureThreshold: 62
          livenessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            # wait for the pod is ready
            initialDelaySeconds: 300
            timeoutSeconds: 5
            periodSeconds: 20
            failureThreshold: 60
          name: oncokb-core-germline-v2
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        workload: lg-general
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: oncokb-core-germline-v2
  name: oncokb-core-germline-v2
spec:
  ports:
    - port: 8888
  selector:
    run: oncokb-core-germline-v2
  type: ClusterIP
