apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gn-vep-pvc-grch38
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 35Gi # volume size requested
