apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: x86-general
spec:
  template:
    metadata:
      labels:
        workload-class: x86-general
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3", "m5", "m6i"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["small", "medium", "large", "xlarge"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: x86-standard
  limits:
    memory: Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
