{
 "title": "cBioPortal ingress + pod stats",
 "description": "Show stats from the kubernetes nginx ingress",
 "tags": [
  "prometheus",
  "nginx"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_bytes_total, instance)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(nginx_requests_total{server_zone!=\"*\", server_zone!=\"_\", instance=~\"^$instance$\"}, server_zone)"
   },
   {
    "name": "upstream",
    "label": "Upstream",
    "query": "label_values(nginx_upstream_bytes_total{instance=~\"^$instance$\"}, upstream)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_connections_total{instance=~\"^$instance$\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_bytes_total{instance=~\"^$instance$\", server_zone=~\"^$host$\", server_zone!=\"*\", server_zone!=\"_\"}[1m])) by (server_zone)",
     "legendFormat": "{{server_zone}}"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_responses_total{instance=~\"^$instance$\", server_zone=~\"^$host$\"}[5m])) by (status_code)",
     "legendFormat": "{{ status_code }} "
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_upstream_responses_total{instance=~\"^$instance$\", upstream =~\"^$upstream$\"}[1m])) by (upstream)",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream Backend Response",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(nginx_upstream_response_msecs_avg{upstream=\"default-cbioportal-http\"})",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "cBioPortal - Replicas",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"cbioportal-spring-boot\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min_over_time(kube_deployment_status_replicas_available{deployment=\"cbioportal-spring-boot\",namespace=\"default\"}[$__interval])",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"cbioportal-spring-boot\",namespace=\"defaulte\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"cbioportal-spring-boot\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"cbioportal-spring-boot\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "cBioPortal (Master i.e. /api/coexpression) - Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"cbioportal-backend-master\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min_over_time(kube_deployment_status_replicas_available{deployment=\"cbioportal-backend-master\",namespace=\"default\"}[$__interval])",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"cbioportal-backend-master\",namespace=\"defaulte\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"cbioportal-backend-master\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"cbioportal-backend-master\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "cBioPortal - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"cbioportal-(spring-boot-|backend-beta|backend-rc|backend-master).*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cBioPortal - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\", pod=~\"cbioportal-(spring-boot-|backend-beta|backend-rc|backend-master).*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cBioPortal - Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"cbioportal-(spring-boot-|backend-beta|backend-rc|backend-master).*\"})",
     "legendFormat": "Total Memory Usage"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"cbioportal-(spring-boot-).*\"})",
     "legendFormat": "Production Only"
    },
    {
     "expr": "(container_memory_usage_bytes{namespace=\"default\", pod=~\"cbioportal-(backend-beta|backend-rc|backend-master).*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Docker Images",
   "type": "table-old",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "kube_pod_container_info{container=~\"cbioportal-(backend|spring).*\"}"
    }
   ]
  }
 ]
}