{
 "title": "OncoKB",
 "description": "Show stats from the kubernetes nginx ingress",
 "tags": [
  "prometheus",
  "nginx",
  "oncokb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_bytes_total, instance)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(nginx_requests_total{server_zone!=\"*\", server_zone!=\"_\", instance=~\"^$instance$\"}, server_zone)"
   },
   {
    "name": "upstream",
    "label": "Upstream",
    "query": "label_values(nginx_upstream_bytes_total{instance=~\"^$instance$\"}, upstream)"
   }
  ]
 },
 "panels": [
  {
   "title": "CronJob Completion Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(kube_job_status_failed{namespace=\"oncokb\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Redis Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{namespace=\"oncokb\", container=~\"oncokb-redis.*\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OncoKB - Public - Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"oncokb-public\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min_over_time(kube_deployment_status_replicas_available{deployment=\"oncokb-public\",namespace=\"oncokb\"}[$__interval])",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"oncokb-public\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"oncokb-public\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"oncokb-public\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "OncoKB - Core - Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"oncokb-core\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min_over_time(kube_deployment_status_replicas_available{deployment=\"oncokb-core\",namespace=\"oncokb\"}[$__interval])",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"oncokb-core\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"oncokb-core\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"oncokb-core\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "OncoKB - Core - Demo - Replicas",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"oncokb-core-demo\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min_over_time(kube_deployment_status_replicas_available{deployment=\"oncokb-core-demo\",namespace=\"oncokb\"}[$__interval])",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"oncokb-core-demo\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"oncokb-core-demo\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"oncokb-core-demo\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "OncoKB - Core - Public - Replicas",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"oncokb-core-public\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min_over_time(kube_deployment_status_replicas_available{deployment=\"oncokb-core-public\",namespace=\"oncokb\"}[$__interval])",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"oncokb-core-public\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"oncokb-core-public\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"oncokb-core-public\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "OncoKB - Core - Beta Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"oncokb-core-beta\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min_over_time(kube_deployment_status_replicas_available{deployment=\"oncokb-cor-beta\",namespace=\"oncokb\"}[$__interval])",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"oncokb-core-beta\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"oncokb-core-beta\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"oncokb-core-beta\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "OncoKB - Core - Legacy - Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"oncokb-core-legacy\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min_over_time(kube_deployment_status_replicas_available{deployment=\"oncokb-core-legacy\",namespace=\"oncokb\"}[$__interval])",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"oncokb-core-legacy\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"oncokb-core-legacy\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"oncokb-core-legacy\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "OncoKB - SOP - Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"oncokb-sop\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min_over_time(kube_deployment_status_replicas_available{deployment=\"oncokb-sop\",namespace=\"oncokb\"}[$__interval])",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"oncokb-sop\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"oncokb-sop\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"oncokb-sop\",namespace=\"oncokb\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "OncoKB - Core - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"oncokb\", container=\"oncokb-core\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OncoKB - Cluster Redis - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"oncokb\", container=\"oncokb-redis-cluster-ng\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OncoKB - Public - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"oncokb\", container=~\"oncokb-public\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OncoKB - Other - CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"oncokb\", container!~\"oncokb-public\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OncoKB - Public - Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"oncokb\", container=\"oncokb-public\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OncoKB - Core - Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"oncokb\", container=\"oncokb-core\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OncoKB - Cluster Redis - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"oncokb\", container=~\"oncokb-redis.*\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by(container) (container_memory_usage_bytes{namespace=\"oncokb\", container=~\"oncokb-redis.*\"})",
     "legendFormat": "{{container}} Total"
    }
   ]
  },
  {
   "title": "OncoKB - Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort(sum by(container) (container_memory_usage_bytes{namespace=\"oncokb\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Images",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "kube_pod_container_info{container=~\"oncokb.*\"}"
    }
   ]
  }
 ]
}