apiVersion: batch/v1
kind: CronJob
metadata:
  name: oncokb-data-save-and-restart
  namespace: oncokb
spec:
  timeZone: "America/New_York"
  schedule: "0 20 * * *" # runs once daily at 8:00 PM
  jobTemplate:
    backoffLimit: 0
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: oncokb-dockerhub-creds
          serviceAccountName: oncokb-staging-restart-sa
          restartPolicy: Never
          containers:
            - name: save-gene-and-restart-staging
              image: "mskcc/oncokb-k8s-with-tools:1.0.0"
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
                - |
                  set -e

                  GENE_ID=4005
                  API_URL="http://oncokb-data-release:8085/api/v1/gene-data"
                  echo "Triggering MySQL refresh using oncokb-data-release server"

                  curl -X POST "${API_URL}/save" \
                    -H "Content-Type: application/json" \
                    --fail \
                    --data "{\"entrezGeneIds\":[${GENE_ID}]}"

                  echo "Polling job status until completion..."
                  while true; do
                    STATUS_JSON=$(curl -s "${API_URL}/status/${GENE_ID}" || echo "")
                    STATUS=$(echo "$STATUS_JSON" | jq -r '.status // empty')
                    ERROR_MSG=$(echo "$STATUS_JSON" | jq -r '.error // empty')

                    if [ "$STATUS" = "succeeded" ]; then
                      echo "Job succeeded"
                      break
                    elif [ "$STATUS" = "failed" ]; then
                      echo "Job failed: ${ERROR_MSG}"
                      exit 1
                    fi
                    sleep 5
                  done

                  echo "Restarting staging core environment"
                  kubectl rollout restart deployment/oncokb-core-curation -n oncokb
          tolerations:
            - key: "workload"
              operator: "Equal"
              value: "oncokb"
              effect: "NoSchedule"
          nodeSelector:
            workload: oncokb
