apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: genie-genome-nexus-mongodump-cronjob
  namespace: genome-nexus
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: aws-cli-credentials
            - configMapRef:
                name: genie-genome-nexus-mongodump-config
            name: genie-genome-nexus-mongodump-cronjob
            image: mongo
            command: ["/bin/sh", "-c"]
            args:
              - echo "Install python";
                apt update; apt install python3 -y;
                echo "Done installing python\n\n";

                echo "Install pip3";
                apt install python3-pip -y;
                echo "Done installing pip3\n\n";

                echo "Install AWS CLI";
                pip3 install awscli --upgrade;
                echo "Done installing AWS CLI\n\n";

                echo "Configure AWS CLI";
                aws configure set aws_access_key_id ${ACCESS_KEY_ID};
                aws configure set aws_secret_access_key ${SECRET_ACCESS_KEY};
                aws configure set default.region ${AWS_REGION};
                echo "Done configuring AWS CLI\n\n";

                MONGODUMP_FILE_NAME=backup_$(date "+%m-%d-%Y-%H-%M-%S").tar.gz;

                echo "Dump mongo database";
                mongodump --uri ${MONGODB_URI} --verbose;
                echo "Done dumping database\n\n";

                echo "Compressing mongo dump";
                tar -zcvf ${MONGODUMP_FILE_NAME} /genie-mongodump;
                echo "Done compressing mongo dump\n\n";

                echo "Move the data to s3";
                aws s3api put-object --bucket ${AWS_S3_BUCKET_NAME} --key ${AWS_S3_BUCKET_DUMP_DIR}/${MONGODUMP_FILE_NAME} --body ${MONGODUMP_FILE_NAME};
                echo "Done moving the database dump\n\n";

                echo "Update contents of latest_mongo_dump.txt";
                echo "${MONGODUMP_FILE_NAME}" > latest_mongo_dump.txt;
                aws s3api put-object --bucket ${AWS_S3_BUCKET_NAME} --key ${AWS_S3_BUCKET_DUMP_DIR}/latest_mongo_dump.txt --body latest_mongo_dump.txt;
                echo "Done updating contents of latest_mongo_dump.txt";

            volumeMounts:
            - mountPath: "/genie-mongodump"
              name: genie-mongodump
          volumes:
          - name: genie-mongodump
            persistentVolumeClaim:
              claimName: genie-genome-nexus-mongodump-pvc
          restartPolicy: OnFailure
