apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: oncokb-public-daily-crobjob
  namespace: oncokb
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: oncokb-public-bot
            name: oncokb-public-daily-crobjob
            image: mysql:5.7
            command: ["/bin/sh", "-c"]
            args:
              - echo "Install curl";
                apt update; apt install curl;
                echo "Done installing curl\n\n";

                echo "API call to send emails to all users whose account will be expired soon";
                curl "http://oncokb-public:9095/api/crobjob/renew-tokens"  -H "Authorization: ${TOKEN}"
                echo "Done calling crobjob/renew-tokens\n\n";

                echo "API call to remove old token stats";
                curl "http://oncokb-public:9095/api/crobjob/remove-old-token-stats"  -H "Authorization: ${TOKEN}"
                echo "Done calling crobjob/remove-old-token-stats\n\n";

                echo "API call to remove old audit events";
                curl "http://oncokb-public:9095/api/crobjob/remove-old-audit-events"  -H "Authorization: ${TOKEN}"
                echo "Done calling crobjob/remove-old-audit-events\n\n";

          restartPolicy: Never
