apiVersion: v1
kind: ConfigMap
metadata:
  name: oncokb-airflow-requirements
  namespace: oncokb
data:
  requirements.txt: "apache-airflow-providers-http==4.1.1\napache-airflow-providers-slack==7.2.0\nredis==4.4.2\nkubernetes==25.3.0\ninflect==6.0.2\n"