---
# Service account for our airflow pods
kind: ServiceAccount
apiVersion: v1
metadata:
  name: oncokb-airflow-serviceaccount
  namespace: oncokb
---
# allow getting status and patching only the one deployment you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oncokb-airflow-role
  namespace: oncokb
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oncokb-airflow-rolebinding
  namespace: oncokb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oncokb-airflow-role
subjects:
  - kind: ServiceAccount
    name: oncokb-airflow-serviceaccount
    namespace: oncokb