# Values for the keycloak Helm release.
fullnameOverride: keycloak-v2

replicas: 2
podDisruptionBudget:
  minAvailable: 1
updateStrategy: RollingUpdate

command:
  - /opt/keycloak/bin/kc.sh

args:
  - start

proxy:
  # Traefik uses X-Forwarded-* headers instead of the standard Forwarded header, so we need to set the mode to xforwarded
  mode: xforwarded

http:
  # For backwards compatibility reasons Helm chart sets this to the value used by previous Keycloak versions.
  # We are fine without this path
  relativePath: "/"

database:
  vendor: mysql

extraInitContainers: |
  - name: theme-provider
    image: mskcc/oncokb-keycloak:1.3.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args:
      - cp -R /themes/keycloak-oncokb/* /keycloak-oncokb && cp -R /themes/curation-login-theme/* /curation-login-theme
    volumeMounts:
      - name: keycloak-oncokb
        mountPath: /keycloak-oncokb
      - name: curation-login-theme
        mountPath: /curation-login-theme

extraVolumeMounts: |
  - name: keycloak-oncokb
    mountPath: /opt/keycloak/themes/keycloak-oncokb
  - name: curation-login-theme
    mountPath: /opt/keycloak/themes/curation-login-theme

extraVolumes: |
  - name: keycloak-oncokb
    emptyDir: {}
  - name: curation-login-theme
    emptyDir: {}

extraEnv: |
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    valueFrom:
      secretKeyRef:
        name: oncokb-keycloak-v2
        key: KEYCLOAK_ADMIN
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: oncokb-keycloak-v2
        key: KEYCLOAK_ADMIN_PASSWORD
  - name: KC_DB_URL_HOST
    valueFrom:
      secretKeyRef:
        name: oncokb-keycloak-v2
        key: DB_ADDRESS
  - name: KC_DB_URL_DATABASE
    valueFrom:
      secretKeyRef:
        name: oncokb-keycloak-v2
        key: DB_DATABASE
  - name: KC_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: oncokb-db-public-rds-admin
        key: DB_USERNAME
  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: oncokb-db-public-rds-admin
        key: DB_PASSWORD
  - name: KC_HOSTNAME
    value: keycloakv2.oncokb.org
  - name: KC_LOG_LEVEL
    value: INFO

resources:
  requests:
    cpu: 500m
    memory: 1000Mi
  limits:
    cpu: "2"
    memory: 1500Mi

# Let's us schedule replicas on the same node, but prefer to schedule them on different nodes if possible
affinity: |
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: keycloakx
              app.kubernetes.io/instance: keycloak
          topologyKey: kubernetes.io/hostname

nodeSelector:
  workload: keycloak

tolerations:
  - key: workload
    operator: Equal
    value: keycloak
    effect: NoSchedule
