apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slide-viewer-wsi-release
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
