apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clinical-trials-matching
  labels:
    run: clinical-trials-matching
  namespace: oncokb
  selfLink: /apis/extensions/v1beta1/namespaces/oncokb/deployments/clinical-trials-matching
spec:
  replicas: 1
  selector:
    matchLabels:
      run: clinical-trials-matching
  template:
    metadata:
      labels:
        run: clinical-trials-matching
    spec:
      containers:
        - name: clinical-trials-matching
          image: victoria34/clinical-trials-matching:0.0.2
          ports:
            - containerPort: 2333
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: clinical-trials-matching
  name: clinical-trials-matching
  namespace: oncokb
  selfLink: /api/v1/namespaces/oncokb/services/clinical-trials-matching
spec:
  ports:
    - port: 2333
      name: http
      targetPort: 2333
  selector:
    run: clinical-trials-matching
  type: ClusterIP
