apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clinical-trials-matching
  labels:
    run: clinical-trials-matching
spec:
  replicas: 1
  selector:
    matchLabels:
      run: clinical-trials-matching
  template:
    metadata:
      labels:
        run: clinical-trials-matching
    spec:
      containers:
        - name: clinical-trials-matching
          image: victoria34/clinical-trials-matching:0.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: clinical-trials-matching
  name: clinical-trials-matching
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    run: clinical-trials-matching
  type: ClusterIP
