apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  generation: 1
  labels:
    run: oncokb-transcript-beta
  name: oncokb-transcript-beta
  namespace: oncokb
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oncokb-transcript-beta
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: oncokb-transcript-beta
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod,api-docs,no-liquibase
            - name: APPLICATION_ONCOKB_URL
              value: 'https://beta.oncokb.org/api/v1'
            - name: APPLICATION_REDIS_ENABLED
              value: 'true'
            - name: APPLICATION_REDIS_TYPE
              value: '$(REDIS_TYPE)'
            - name: APPLICATION_REDIS_ADDRESS
              value: '$(REDIS_ADDRESS)'
            - name: APPLICATION_REDIS_PASSWORD
              value: '$(REDIS_PASSWROD)'
            - name: APPLICATION_REDIS_SENTINEL_MASTER_NAME
              value: '$(REDIS_MASTERNAME)'
          envFrom:
            - configMapRef:
                name: oncokb-transcript-beta
            - configMapRef:
                name: oncokb-sentinel-redis
          image: oncokb/oncokb-transcript:0.7.0-alpha.2
          imagePullPolicy: Always
          # use actionable variants endpoint to cache everything
          readinessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 3000
          name: oncokb-transcript-beta
          ports:
            - name: http
              containerPort: 9090
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: oncokb-transcript-beta
  namespace: oncokb
spec:
  ports:
  - port: 9090
    name: http
    targetPort: 9090
  selector:
    run: oncokb-transcript-beta
  type: ClusterIP
