apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncokb-public
  namespace: oncokb
spec:
  replicas: 4
  selector:
    matchLabels:
      app: oncokb-public
      version: 'v1'
  strategy:
    rollingUpdate:
      maxSurge: 6
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oncokb-public
        version: 'v1'
    spec:
      containers:
        - name: oncokb-public
          image: oncokb/oncokb-public:2.7.3
          env:
            # Database schema update takes a lot of especially when changing a table with a lot of table
            # We should disable the liveness prob to avoid the pod to be terminated before the liquibase finish all the work
            - name: SPRING_PROFILES_ACTIVE
              value: prod,no-liquibase
            - name: JAVA_OPTS
              value: '-Xmx1024m -Xms512m'
            - name: APPLICATION_AWS_S3_ACCESS_KEY
              value: '$(ACCESS_KEY_ID)'
            - name: APPLICATION_AWS_S3_REGION
              value: '$(AWS_REGION)'
            - name: APPLICATION_AWS_S3_SECRET_KEY
              value: '$(SECRET_ACCESS_KEY)'
          envFrom:
            - configMapRef:
                name: oncokb-public
            - configMapRef:
                name: aws-cli-credentials
          readinessProbe:
            httpGet:
              path: /v2/api-docs
              port: 9095
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 9095
            initialDelaySeconds: 90
            timeoutSeconds: 15
            periodSeconds: 15
            failureThreshold: 10
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 750m
          ports:
            - name: http
              containerPort: 9095

---
apiVersion: v1
kind: Service
metadata:
  name: oncokb-public
  namespace: oncokb
  labels:
    app: oncokb-public
spec:
  selector:
    app: oncokb-public
  type: ClusterIP
  ports:
    - name: http
      port: 9095
