controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      # Enter the ARN of the ACM certificate
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:762447640649:certificate/a6f290b0-9193-4dc3-bf7a-df2048b223e1
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
      # The timestamp of the last update is used to recreate resources if no config has been changed
      # kubectl annotate svc oncokb-ingress-nginx-controller last-update=$(date +%s) --overwrite
      last-update: 1692622798
    targetPorts:
      # SSL termination at load balancer, so targetPort of https should be 80
      https: 80
