controller:
  extraArgs:
    default-ssl-certificate: null
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      # Enter the ARN of the ACM certificate
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:[REDACTED]:certificate/[REDACTED]
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
      # The timestamp of the last update is used to recreate resources if no config has been changed
      # kubectl annotate svc oncokb-ingress-nginx-controller last-update=$(date +%s) --overwrite
      last-update: 1692373285
    targetPorts:
      # SSL termination at load balancer, so targetPort of https should be 80
      https: 80
