apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oncokb
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`demo.oncokb.org`)
      services:
        - name: oncokb-core-demo
          port: 80
    - kind: Rule
      match: Host(`public.api.oncokb.org`)
      services:
        - name: oncokb-core-public
          port: 80
    - kind: Rule
      match: Host(`sop.oncokb.org`)
      services:
        - name: oncokb-sop
          port: 4321
    - kind: Rule
      match: Host(`curation.oncokb.org`)
      services:
        - name: oncokb-curation
          port: 9090
    - kind: Rule
      match: Host(`keycloak.oncokb.org`)
      services:
        - name: keycloak-http
          port: 80
    - kind: Rule
      match: Host(`staging.oncokb.org`)
      services:
        - name: oncokb-public-staging
          port: 9095
    - kind: Rule
      match: Host(`oncokb2.oncokb.org`)
      services:
        - name: oncokb-public
          port: 9095
    - kind: Rule
      match: Host(`airflow2.oncokb.org`)
      services:
        - name: oncokb-airflow-web
          port: 8080
  tls:
    secretName: oncokb-cert-secret
