apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oncokb
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`demo.oncokb.org`)
      services:
        - name: oncokb-core-demo
          port: 80
    - kind: Rule
      match: Host(`public.api.oncokb.org`)
      services:
        - name: oncokb-core-public
          port: 80
    - kind: Rule
      match: Host(`sop.oncokb.org`)
      services:
        - name: oncokb-sop
          port: 4321
    - kind: Rule
      match: Host(`curation2.oncokb.org`)
      services:
        - name: oncokb-curation
          port: 9090
  tls:
    secretName: oncokb-cert-secret
