global:
  security:
    allowInsecureImages: true
  imagePullSecrets:
    - oncokb-dockerhub-creds

image:
  registry: docker.io
  repository: bitnamilegacy/redis

architecture: replication

auth:
  enabled: true
  existingSecret: redis-cluster
  existingSecretPasswordKey: REDIS_PASSWORD

persistence:
  enabled: true
  storageClass: efs-sc
  accessModes:
    - ReadWriteMany
  size: 4Gi

master:
  nodeSelector:
    workload: curation
  tolerations:
    - key: workload
      value: curation
      operator: Equal
      effect: NoSchedule

replica:
  nodeSelector:
    workload: curation
  tolerations:
    - key: workload
      value: curation
      operator: Equal
      effect: NoSchedule
