apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-ingress-class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.middlewares: default-uablock-browser@kubernetescrd
  labels:
    app.kubernetes.io/instance: cbioportal-api
  name: cbioportal-api-ingress
  namespace: default
spec:
  rules:
    - host: api.cbioportal.org
      http:
        paths:
          - backend:
              service:
                name: cbioportal-backend-public-api-blue
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - api.cbioportal.org
      secretName: api-cbio-cert
