apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: gn-spring-boot-beta
  name: gn-spring-boot-beta
  namespace: genome-nexus
  selfLink: /apis/extensions/v1beta1/namespaces/genome-nexus/deployments/gn-spring-boot-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gn-spring-boot-beta
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gn-spring-boot-beta
    spec:
      # volumes:
      #   - name: gn-documentdb-config-volume
      #     configMap:
      #       name: gn-documentdb-config
      containers:
      - env:
        - name: SERVER_PORT
          value: "8888"
        - name: MONGODB_URI
          # working version
          # value: mongodb://gnadmin:supersecretpwforgn@genome-nexus-db.cluster-cq26ederqvxp.us-east-1.docdb.amazonaws.com:27017/annotator?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
          value: mongodb://gn-mongo-v0dot21-mongodb:27017/annotator?connectTimeoutMS=120000

          # test
          # value: mongodb://gnadmin:supersecretpwforgn@genome-nexus-db.cluster-cq26ederqvxp.us-east-1.docdb.amazonaws.com:27017/annotator?replicaSet=rs0

          # value: mongodb://genome-nexus-db.cluster-cq26ederqvxp.us-east-1.docdb.amazonaws.com:27017/annotator
          # value: mongodb://gnadmin:supersecretpwforgn@genome-nexus-db.cq26ederqvxp.us-east-1.docdb.amazonaws.com:27017,genome-nexus-db.cluster-cq26ederqvxp.us-east-1.docdb.amazonaws.com:27017/annotator?replicaSet=rs0
          # value: mongodb://gnadmin:supersecretpwforgn@genome-nexus-db.cluster-cq26ederqvxp.us-east-1.docdb.amazonaws.com:27017/annotator?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
          # value: mongodb://gnadmin:supersecretpwforgn@genome-nexus-db.cluster-cq26ederqvxp.us-east-1.docdb.amazonaws.com:27017/annotator?ssl=true&ssl_ca_certs=/documentdb/rds-ca-2019-root.pem
          # value: mongodb://gn-mongo-v0dot21-mongodb:27017/annotator?connectTimeoutMS=120000
        - name: SENTRY_DSN
          valueFrom: 
            secretKeyRef:
              name: genome-nexus-sentry-dsn
              key: dsn
        # volumeMounts:
        #   - name: gn-documentdb-config-volume
        #     mountPath: /documentdb/
        image: leexdocker/gn-spring-boot:test-documentdb-log-fetch-one-by-one-variant
        imagePullPolicy: Always
        command: [ "java" ]
        args: [
            # use ZGC (shenandoah like GC, openjdk (Oracle) image does not
            # include shenandoah)
            "-Xms100m",
            "-Xmx8g",
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+UseZGC",
            "-Dspring.data.mongodb.uri=$(MONGODB_URI)",
            # this is to use VEP running inside K8s. Remove to use
            # grch37.rest.ensembl.org instead
            # "-Dgn_vep.region.url=http://gn-vep/vep/human/region/VARIANT",
            "-jar",
            "/app.war"
        ]
        readinessProbe:
          httpGet:
            path: /ensembl/canonical-transcript/hgnc/tp53?isoformOverrideSource=uniprot
            port: 8888
          initialDelaySeconds: 240
          timeoutSeconds: 30
          periodSeconds: 60
        # TODO: create a better liveness probe (this is just readiness with
        # more lenience)
        livenessProbe:
          httpGet:
            path: /ensembl/canonical-transcript/hgnc/tp53?isoformOverrideSource=uniprot
            port: 8888
          initialDelaySeconds: 240
          timeoutSeconds: 120
          periodSeconds: 240
        name: gn-spring-boot-beta
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
          requests:
              memory: 10Gi
          limits:
              memory: 20Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # run on genome nexus machines
      nodeSelector:
         kops.k8s.io/instancegroup: genome-nexus
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: gn-spring-boot-beta
    app: gn-spring-boot-beta
  name: genome-nexus-beta
  namespace: genome-nexus
  selfLink: /api/v1/namespaces/genome-nexus/services/genome-nexus-beta
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  - port: 443
    name: https
    targetPort: 8888
  selector:
    run: gn-spring-boot-beta
  type: ClusterIP
