apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: oncokb-daily-usage-analysis-cronjob
  namespace: oncokb
spec:
  schedule: "0 1 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: aws-cli-credentials
            - configMapRef:
                name: oncokb-usage-analysis-config
            name: oncokb-daily-usage-analysis
            image: oncokb/oncokb-usage-analysis:0.0.2
            command: ["/bin/bash", "-c"]
            args:
              - service mysql start;
                mysql -e "ALTER USER '${MYSQL_USER}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${MYSQL_PASSWORD}'";
                mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -Bse "use mysql;update user set host = '%' where user = 'root' and host ='localhost';flush privileges;";
                python3 src/main.py
          restartPolicy: Never