controller:
  enableAnnotationValidations: false
  allowSnippetAnnotations: true
  extraArgs:
    maxmind-edition-ids: GeoLite2-Country
  config:
    use-geoip: "false"
    use-geoip2: "true"
    http-snippet: |
      map $geoip2_country_code $allowed_country {
        default yes;
        IR no;
        KP no;
        CU no;
        CN no;
        RU no;
        VE no;
      }
    annotations-risk-level: Critical
    client-header-buffers: 16k
    large-client-header-buffers: 4 16k
    log-format-escape-json: "true"
    # use output format that can be parsed by fluentd:
    # https://github.com/kubernetes/ingress-nginx/issues/1664
    log-format-upstream: '{"proxy_protocol_addr": "$proxy_protocol_addr","remote_addr":
      "$remote_addr", "proxy_add_x_forwarded_for": "$proxy_add_x_forwarded_for", "remote_user":
      "$remote_user", "time_local": "$time_local", "request" : "$request", "status":
      $status, "body_bytes_sent": $body_bytes_sent, "http_referer": "$http_referer",
      "http_user_agent": "$http_user_agent", "request_length" : $request_length,
      "request_time" : $request_time, "proxy_upstream_name": "$proxy_upstream_name",
      "upstream_addr": "$upstream_addr", "upstream_response_length": $upstream_response_length,
      "upstream_response_time": $upstream_response_time, "upstream_status": $upstream_status}'
    proxy-body-size: 1024m
    proxy-buffer-size: 16k
    proxy-buffers: 16k
    proxy-connect-timeout: "300"
    proxy-read-timeout: "300"
    proxy-send-timeout: "300"
    use-proxy-protocol: "true"
  image:
    tag: 1.12.1
  metrics:
    enabled: true
  replicaCount: 2
  nodeSelector:
    workload: ingress
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "ingress"
      effect: "NoSchedule"
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  stats:
    enabled: true
rbac:
  create: true
