apiVersion: v1
kind: PersistentVolume
metadata:
  name: gn_mongodb_grch37_v1dot0_pv
  namespace: genome-nexus
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: vol-0c06de89da743da1b
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gn_mongodb_grch37_v1dot0_pvc
  namespace: genome-nexus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 300Gi
  volumeName: gn_mongodb_grch37_v1dot0_pv