apiVersion: v1
kind: PersistentVolume
metadata:
  name: gn-mongodb-grch37-v1dot0-pv
  namespace: genome-nexus
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0c06de89da743da1b
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-east-1b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gn-mongodb-grch37-v1dot0-pvc
  namespace: genome-nexus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 300Gi
  volumeName: gn-mongodb-grch37-v1dot0-pv