apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: eks-private
    tags.datadoghq.com/env: eks-private
    tags.datadoghq.com/service: cbioportal
    tags.datadoghq.com/version: 6.1.0
  name: eks-private
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eks-private
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eks-private
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: eks-private
        tags.datadoghq.com/env: eks-private
        tags.datadoghq.com/service: cbioportal
        tags.datadoghq.com/version: 6.1.0
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.24.2
    spec:
      volumes:
        - name: private-eks-configmap-volume
          configMap:
            name: eks-v6-shared-kc-dec-2029
            items:
              - key: local.key
                path: local.key
              - key: local.crt
                path: local.crt
      containers:
      - envFrom:
        - configMapRef:
            name: private-eks-v6
        env:
          - name: PORTAL_HOME
            value: /cbioportal/
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "true"
        image: cbioportal/cbioportal:6.1.0-web-shenandoah
        volumeMounts:
          - name: private-eks-configmap-volume
            mountPath: /cbioportal/local.key
            subPath: local.key
          - name: private-eks-configmap-volume
            mountPath: /cbioportal/local.crt
            subPath: local.crt
        command: [ "java" ]
        args: [
            # from https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
            "-Xms100m",
            "-Xmx15g",
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+UseShenandoahGC",
            "-XX:ShenandoahUncommitDelay=1000",
            "-XX:ShenandoahGuaranteedGCInterval=10000",
            #"-XX:+AlwaysPreTouch",
            #"-XX:+UseTransparentHugePages",
            #"-XX:+UseNUMA",
            #"-XX:+PrintGCDetails",
            #"-XX:+UseParallelGC",
            #"-XX:+PrintGCDateStamps",
            #"-XX:ParallelGCThreads=4",
            #"-XX:+UseG1GC",
            #"-XX:+AggressiveHeap",
            # non aggressive garbage collection
            #"-XX:MinHeapFreeRatio=20",
            #"-XX:MaxHeapFreeRatio=40",
            #"-XX:GCTimeRatio=19",
            #"-XX:AdaptiveSizePolicyWeight=90",
            # This issue says to use maxRAMFraction > 1
            # https://github.com/akka/akka/issues/23499, but haven't found this
            # to work v well
            #"-XX:MaxRAMFraction=1",
            "-XX:+PrintFlagsFinal",
            "-XshowSettings:vm",
            # need to set MaxRAM, somehow the MaxRAMFraction is not picked up
            # from the limits
            #"-XX:MaxRAM=6500m",
            "-jar",
            "/cbioportal-webapp/app.jar",
            # handles legacy swagger urls after upgrade
            "--springdoc.swagger-ui.disable-swagger-default-url=true",
            "--springdoc.swagger-ui.path=/api/swagger-ui",
            "--springdoc.api-docs.path=/api/v3/api-docs",
            # enable remote debug
            "--com.sun.management.jmxremote.rmi.port=8849",
            "--com.sun.management.jmxremote=false",
            "--com.sun.management.jmxremote.port=8849",
            "--com.sun.management.jmxremote.ssl=false",
            "--com.sun.management.jmxremote.authenticate=false",
            "--com.sun.management.jmxremote.local.only=false",
            "--java.rmi.server.hostname=localhost",
            # /enable remote debug
            "--frontend.url=https://frontend.cbioportal.org/",
            "--default_cross_cancer_study_session_id=5c8a7d55e4b046111fee2296",
            "--quick_search.enabled=true",
            "--skin.footer=",
            "--skin.right_nav.whats_new_blurb=",
            "--skin.quick_select_buttons=TCGA PanCancer Atlas Studies#*pan_can_atlas*;Curated set of non-redundant studies|227 studies that are manually curated including TCGA and non-TCGA studies with no overlapping samples#acbc_mskcc_2015,acc_tcga_pan_can_atlas_2018,acyc_fmi_2014,acyc_mda_2015,acyc_mskcc_2013,acyc_sanger_2013,all_phase2_target_2018_pub,all_stjude_2016,aml_target_2018_pub,ampca_bcm_2016,angs_project_painter_2018,bfn_duke_nus_2015,blca_bgi,blca_cornell_2016,blca_dfarber_mskcc_2014,blca_mskcc_solit_2012,blca_mskcc_solit_2014,blca_tcga_pan_can_atlas_2018,brca_bccrc,brca_broad,brca_igr_2015,brca_mbcproject_wagle_2017,brca_metabric,brca_sanger,brca_tcga_pan_can_atlas_2018,ccrcc_irc_2014,ccrcc_utokyo_2013,cesc_tcga_pan_can_atlas_2018,chol_jhu_2013,chol_nccs_2013,chol_nus_2012,chol_tcga_pan_can_atlas_2018,cll_iuopa_2015,cllsll_icgc_2011,coadread_dfci_2016,coadread_genentech,coadread_mskcc,coadread_tcga_pan_can_atlas_2018,cscc_dfarber_2015,cscc_hgsc_bcm_2014,ctcl_columbia_2015,desm_broad_2015,dlbc_tcga_pan_can_atlas_2018,dlbcl_dfci_2018,dlbcl_duke_2017,egc_tmucih_2015,es_dfarber_broad_2014,es_iocurie_2014,esca_broad,esca_tcga_pan_can_atlas_2018,escc_icgc,escc_ucla_2014,gbc_shanghai_2014,gbm_tcga_pan_can_atlas_2018,glioma_msk_2018,hcc_inserm_fr_2015,hcc_msk_venturaa_2018,hnsc_broad,hnsc_jhu,hnsc_mdanderson_2013,hnsc_tcga_pan_can_atlas_2018,kich_tcga_pan_can_atlas_2018,kirc_bgi,kirc_tcga_pan_can_atlas_2018,kirp_tcga_pan_can_atlas_2018,laml_tcga_pan_can_atlas_2018,lcll_broad_2013,lgg_tcga_pan_can_atlas_2018,lgg_ucsf_2014,liad_inserm_fr_2014,lihc_amc_prv,lihc_riken,lihc_tcga_pan_can_atlas_2018,luad_broad,luad_tcga_pan_can_atlas_2018,luad_tsp,lusc_tcga_pan_can_atlas_2018,mbl_broad_2012,mbl_pcgp,mbl_sickkids_2016,mcl_idibips_2013,mds_tokyo_2011,mel_tsam_liang_2017,meso_tcga_pan_can_atlas_2018,mixed_allen_2018,mixed_pipseq_2017,mm_broad,mpnst_mskcc,mrt_bcgsc_2016,mskimpact,nbl_amc_2012,nbl_target_2018_pub,nbl_ucologne_2015,nccrcc_genentech_2014,nepc_wcm_2016,nhl_bcgsc_2011,nhl_bcgsc_2013,npc_nusingapore,nsclc_unito_2016,ov_tcga_pan_can_atlas_2018,paac_jhu_2014,paad_qcmg_uq_2016,paad_tcga_pan_can_atlas_2018,paad_utsw_2015,pact_jhu_2011,panet_arcnet_2017,panet_jhu_2011,panet_shanghai_2013,pcnsl_mayo_2015,pcpg_tcga_pan_can_atlas_2018,pediatric_dkfz_2017,plmeso_nyu_2015,prad_broad,prad_eururol_2017,prad_fhcrc,prad_mich,prad_mpcproject_2018,prad_mskcc,prad_mskcc_cheny1_organoids_2014,prad_tcga_pan_can_atlas_2018,rms_nih_2014,rt_target_2018_pub,sarc_mskcc,sarc_tcga_pan_can_atlas_2018,scco_mskcc,sclc_cancercell_gardner_2017,sclc_jhu,sclc_ucologne_2015,skcm_broad,skcm_broad_brafresist_2012,skcm_tcga_pan_can_atlas_2018,skcm_vanderbilt_mskcc_2015,skcm_yale,stad_pfizer_uhongkong,stad_tcga_pan_can_atlas_2018,stad_utokyo,summit_2018,tet_nci_2014,tgct_tcga_pan_can_atlas_2018,thca_tcga_pan_can_atlas_2018,thym_tcga_pan_can_atlas_2018,uccc_nih_2017,ucec_tcga_pan_can_atlas_2018,ucs_jhu_2014,ucs_tcga_pan_can_atlas_2018,um_qimr_2016,urcc_mskcc_2016,utuc_mskcc_2015,uvm_tcga_pan_can_atlas_2018,vsc_cuk_2018,wt_target_2018_pub,acyc_jhu_2016,prostate_dkfz_2018,histiocytosis_cobi_msk_2019,utuc_cornell_baylor_mdacc_2019,prad_su2c_2019,cll_broad_2015,coad_cptac_2019,brca_mskcc_2019,acc_2019,pptc_2019,prad_msk_2019,ccrcc_dfci_2019,mpn_cimr_2013,nsclc_tracerx_2017,mnm_washu_2016,bcc_unige_2016,coad_caseccc_2015,metastatic_solid_tumors_mich_2017,aml_ohsu_2018,ihch_smmu_2014,nsclc_mskcc_2018,skcm_dfci_2015,skcm_mskcc_2014,mel_ucla_2016,utuc_msk_2019,gbm_columbia_2019,stad_oncosg_2018,brca_smc_2018,luad_oncosg_2020,angs_painter_2020,mel_dfci_2019,lung_smc_2016,utuc_igbmc_2021,cscc_ucsf_2021,chol_icgc_2017,hccihch_pku_2019,ihch_ismms_2015,mbl_dkfz_2017,pan_origimed_2020,crc_nigerian_2020,difg_glass_2019,pancan_pcawg_2020,ucec_cptac_2020,paad_cptac_2021,lusc_cptac_2021,luad_cptac_2020,gbm_cptac_2021,brca_cptac_2020,brain_cptac_2020,mpcproject_broad_2021,brca_hta9_htan_2022,lung_nci_2022,mds_iwg_2022,biliary_tract_summit_2022,pog570_bcgsc_2020,hcc_meric_2021,prostate_pcbm_swiss_2019,ucec_ccr_cfdna_msk_2022,ucec_ccr_msk_2022,mixed_selpercatinib_2020,lgsoc_mapk_msk_2022,mng_utoronto_2021,blca_bcan_hcrn_2022,aml_ohsu_2022,coad_silu_2022,stmyec_wcm_2022,bladder_columbia_msk_2018,sarcoma_msk_2022,cll_broad_2022,coadread_cass_2020,prad_msk_mdanderson_2023,hcc_clca_2024,brca_fuscc_2020,brca_dfci_2020,chl_sccc_2023,sarcoma_ucla_2024",
            "--skin.example_study_queries=tcga pancancer atlas\ntcga -legacy -pancancer\ntcga or icgc\nmsk-impact\n-\"cell line\"\nbreast\nesophageal OR stomach\nprostate msk\nserous",
            "--skin.patientview.filter_genes_profiled_all_samples=false",
            "--installation_map_url=https://installationmap.netlify.app/",
            "--app.name=eks-private",
            "--filter_groups_by_appname=false",
            "--enable_cross_study_expression=(studies)=>studies.filter(s=>/pan_can_atlas/.test(s.studyId) === false).length === 0",
            # connecting over dbcp
            "--dbconnector=dbcp",
            "--authenticate=saml",
            "--authorization=false",
            "--security.cors.allowed-origins=*",
            "--db.user=$(DB_USER)",
            "--db.password=$(DB_PASSWORD)",
            "--db.suppress_schema_version_mismatch_errors=true",
            "--spring.datasource.driver-class-name=com.mysql.jdbc.Driver",
            "--spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect",
            "--spring.datasource.url=jdbc:mysql://$(DB_HOST):3306/$(DB_PORTAL_DB_NAME)?zeroDateTimeBehavior=convertToNull&useSSL=false",
            "--spring.datasource.username=$(DB_USER)",
            "--spring.datasource.password=$(DB_PASSWORD)",
            "--tomcat.catalina.scope=runtime",
            "--show.transcript_dropdown=true",
            "--skin.show_tweet_button=$(SKIN_SHOW_TWEET_BUTTON)",
            "--skin.email_contact=cdsi@mskcc.org",
            "--skin.data_sets_footer=Data sets of published studies were curated from literature. Data sets of legacy TCGA studies were downloaded from the <a href=\"http://gdac.broadinstitute.org\">Broad Institute Firehose</a>, last updated 1/28/2016.",
            "--skin.data_sets_header=The table below lists the number of available samples per cancer study and data type.",
            "--skin.authorization_message=Welcome to cBioPortal. Logging in will allow you to access your studies and groups from any computer, and cBioPortal will also remember your study view charts preferences for each study (i.e. order of the charts, type of charts and visibility). Login is optional and not required to access any of the other features of cBioPortal.",
            "--skin.blurb=",
            "--show.mdacc.heatmap=true",
            "--priority_studies=PanCancer Studies#msk_impact_2017,metastatic_solid_tumors_mich_2017,mixed_allen_2018,summit_2018,tmb_mskcc_2018,ntrk_msk_2019,msk_ch_2020;Pediatric Cancer Studies#pptc_2019,all_phase2_target_2018_pub,rt_target_2018_pub,wt_target_2018_pub,aml_target_2018_pub,nbl_target_2018_pub,pediatric_dkfz_2017,mixed_pipseq_2017,all_stjude_2016,all_stjude_2015,es_dfarber_broad_2014,es_iocurie_2014,mbl_pcgp;Immunogenomic Studies#gbm_columbia_2019,skcm_dfci_2015,skcm_mskcc_2014,mel_ucla_2016,nsclc_mskcc_2018,nsclc_mskcc_2015,tmb_mskcc_2018,ccrcc_dfci_2019;Cell lines#ccle_broad_2019,cellline_ccle_broad,cellline_nci60",
            "--session.service.url=https://session-service.cbioportal.org/api/sessions/private_portal/",
            "--session.service.origin=*",
            "--session.service.user=$(SESSION_SERVICE_USER_NAME)",
            "--session.service.password=$(SESSION_SERVICE_USER_PASSWORD)",
            "--google_analytics_profile_id=$(GOOGLE_ANALYTICS_PROFILE_ID)",
            "--googleplus.consumer.key=$(GOOGLE_PLUS_CONSUMER_KEY)",
            "--googleplus.consumer.secret=$(GOOGLE_PLUS_CONSUMER_SECRET)",
            "--microsoftlive.consumer.key=$(MICROSOFT_LIVE_CONSUMER_KEY)",
            "--microsoftlive.consumer.secret=$(MICROSOFT_LIVE_CONSUMER_SECRET)",
            "--bitly.url=$(BITLY_URL)",
            "--bitly.access.token=$(BITLY_ACCESS_TOKEN)",
            "--sentry.dsn=$(SENTRY_DSN)",
            "--sentry.factory=org.cbioportal.logging.SentryClientFactory",
            #"--sentryjs.frontend_project_endpoint=$(SENTRY_FRONTEND_DSN)",
            "--sitemaps=true",
            "--oncokb.public_api.url=https://core.oncokb.aws.mskcc.org/api/v1",
            # token is not needed to access MSK OncoKB instance
            "--oncokb.token=fake_token",
            "--oncokb.merge_icons_by_default=false",
            "--genomenexus.url=https://v1.genomenexus.org",
            "--show.genomenexus.annotation_sources=mutation_assessor",
            "--matchminer.url=http://ec2-54-158-52-176.compute-1.amazonaws.com:5555",
            "--matchminer.token=$(MATCHMINER_TOKEN)",
            # redis session store settings (different from redis persistence cache)
            "--spring.session.store-type=redis",
            "--spring.data.redis.host=$(REDIS_SESSION_HOST)",
            "--spring.data.redis.port=$(REDIS_SESSION_PORT)",
            "--spring.data.redis.password=$(REDIS_SESSION_PASSWORD)",
            # To enable redis session store, we need to set
            # spring.autoconfigure.exclude to a random value to override the
            # property in applications.properties.EXAMPLE
            "--spring.autoconfigure.exclude=dontexcludeanythingplz",
            # cache settings (currently redis)
#            "--cache.statistics_endpoint_enabled=false",
            "--redis.database=1",
            "--persistence.cache_type=redis",
            "--redis.leader_address=redis://cbioportal-persistence-redis-master:6379",
            "--redis.follower_address=redis://cbioportal-persistence-redis-replicas:6379",
            "--redis.password=$(REDIS_PASSWORD)",
            "--ehcache.cache_type=none",
            "--cache.endpoint.api-key=$(CACHE_API_KEY)",
            "--cache.endpoint.enabled=true",
            "--redis.clear_on_startup=false",
            # misc frontend settings (this is NOT for backend persistence layer caching)
            "--enable_persistent_cache=false",
            # Disable study tags fetch
            "--enable_study_tags=false",
            # auth
            # "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.assertingparty.metadata-uri=/cbioportal/msk-beta-cbioportal-saml-idp-metadata.xml",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.assertingparty.metadata-uri=https://keycloak.cbioportal.mskcc.org/auth/realms/external/protocol/saml/descriptor",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.entity-id=private-v6",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.signing.credentials[0].certificate-location=file:/cbioportal/local.crt",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.signing.credentials[0].private-key-location=file:/cbioportal/local.key",
            # "--logging.level.org.springframework.security=DEBUG",
            # "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.singlelogout.binding=POST",
            # "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.singlelogout.response-url=http://localhost:8080/logout/saml2/slo",
            # compress on client side
            "--enable_request_body_gzip_compression=true",
            # this addresses same issue as
            # https://github.com/cBioPortal/cbioportal/issues/2328 one needs to
            # set this if one doesn't want to forward https -> http -> https
            # when logging in through google auth. Somehow this goes over http
            # otherwise.
#            "--proxy-base-url",
#            "https://private.cbioportal.mskcc.org:443",
#            "--max-threads",
#            "0",
#            "--session-store",
#            "redis",
#            "--session-store-operation-timeout",
#            "10000",
#            # Fix long URL https://github.com/cBioPortal/cbioportal/issues/5836
#            "-AmaxHttpHeaderSize=16384",
#            "-AconnectionTimeout=20000",
#            "--enable-compression",
#            "--port",
#            "8888",
            "--server.compression.enabled=true",
            "--server.tomcat.connection-timeout=20000",
            "--server.tomcat.max-http-response-header-size=16384",
            "--server.max-http-request-header-size=16384",
            "--server.port=8888",
        ]
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8888
          initialDelaySeconds: 45
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 15
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8888
          initialDelaySeconds: 180
          timeoutSeconds: 2
          periodSeconds: 12
          failureThreshold: 20
        name: eks-private
        ports:
        - containerPort: 8888
          protocol: TCP
        - containerPort: 8849
          protocol: TCP
        resources:
          requests:
              cpu: 1500m
              memory: 10Gi
          limits:
              memory: 16Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: large-memory-portals
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: eks-private
  name: eks-private
  selfLink: /api/v1/namespaces/default/services/eks-private
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    run: eks-private
  type: ClusterIP
