apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: eks-sclc
    tags.datadoghq.com/env: eks-sclc
    tags.datadoghq.com/service: cbioportal
    tags.datadoghq.com/version: 6.3.3
  name: eks-sclc
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eks-sclc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eks-sclc
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: eks-sclc
        tags.datadoghq.com/env: eks-sclc
        tags.datadoghq.com/service: cbioportal
        tags.datadoghq.com/version: 6.3.3
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.24.2
    spec:
      volumes:
      - name: sclc-eks-configmap-volume
        configMap:
          name: eks-v6-shared-kc-dec-2029
          items:
          - key: local.key
            path: local.key
          - key: local.crt
            path: local.crt
      containers:
      - envFrom:
        - configMapRef:
            name: sclc-eks-v6
        env:
        - name: PORTAL_HOME
          value: /cbioportal/
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        image: cbioportal/cbioportal-dev:0ca764de1fecf054a1ef6e8a74a72ce211052c33-web-shenandoah
        volumeMounts:
        - name: sclc-eks-configmap-volume
          mountPath: /cbioportal/local.key
          subPath: local.key
        - name: sclc-eks-configmap-volume
          mountPath: /cbioportal/local.crt
          subPath: local.crt
        command: [ "java" ]
        args: [
            # from https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
            "-Xms100m",
            "-Xmx4g",
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+UseShenandoahGC",
            "-XX:ShenandoahUncommitDelay=1000",
            "-XX:ShenandoahGuaranteedGCInterval=10000",
            #"-XX:+AlwaysPreTouch",
            #"-XX:+UseTransparentHugePages",
            #"-XX:+UseNUMA",
            #"-XX:+PrintGCDetails",
            #"-XX:+UseParallelGC",
            #"-XX:+PrintGCDateStamps",
            #"-XX:ParallelGCThreads=4",
            #"-XX:+UseG1GC",
            #"-XX:+AggressiveHeap",
            # non aggressive garbage collection
            #"-XX:MinHeapFreeRatio=20",
            #"-XX:MaxHeapFreeRatio=40",
            #"-XX:GCTimeRatio=19",
            #"-XX:AdaptiveSizePolicyWeight=90",
            # This issue says to use maxRAMFraction > 1
            # https://github.com/akka/akka/issues/23499, but haven't found this
            # to work v well
            #"-XX:MaxRAMFraction=1",
            "-XX:+PrintFlagsFinal",
            "-XshowSettings:vm",
            # need to set MaxRAM, somehow the MaxRAMFraction is not picked up
            # from the limits
            #"-XX:MaxRAM=6500m",
            "-jar",
            "/cbioportal-webapp/app.jar",
            # handles legacy swagger urls after upgrade
            "--springdoc.swagger-ui.disable-swagger-default-url=true",
            "--springdoc.swagger-ui.path=/api/swagger-ui",
            "--springdoc.api-docs.path=/api/v3/api-docs",
            # enable remote debug
            "--com.sun.management.jmxremote.rmi.port=8849",
            "--com.sun.management.jmxremote=false",
            "--com.sun.management.jmxremote.port=8849",
            "--com.sun.management.jmxremote.ssl=false",
            "--com.sun.management.jmxremote.authenticate=false",
            "--com.sun.management.jmxremote.local.only=false",
            "--java.rmi.server.hostname=0.0.0.0",
            "--frontend.url=https://frontend.cbioportal.org/",
            "--quick_search.enabled=true",
            "--skin.footer=",
            "--skin.right_nav.whats_new_blurb=",
            "--skin.example_study_queries=tcga pancancer atlas\ntcga -legacy -pancancer\ntcga or icgc\nmsk-impact\n-\"cell line\"\nbreast\nesophageal OR stomach\nprostate msk\nserous",
            "--priority_studies=PanCancer Studies#sclc_mskimpact_2017,msk_impact_2017,metastatic_solid_tumors_mich_2017,mixed_allen_2018,summit_2018,tmb_mskcc_2018,ntrk_msk_2019,msk_ch_2020;Pediatric Cancer Studies#pptc_2019,all_phase2_target_2018_pub,rt_target_2018_pub,wt_target_2018_pub,aml_target_2018_pub,nbl_target_2018_pub,pediatric_dkfz_2017,mixed_pipseq_2017,all_stjude_2016,all_stjude_2015,es_dfarber_broad_2014,es_iocurie_2014,mbl_pcgp;Immunogenomic Studies#gbm_columbia_2019,skcm_dfci_2015,skcm_mskcc_2014,mel_ucla_2016,nsclc_mskcc_2018,nsclc_mskcc_2015,tmb_mskcc_2018,ccrcc_dfci_2019;Cell lines#ccle_broad_2019,cellline_ccle_broad,cellline_nci60",
            "--skin.patientview.filter_genes_profiled_all_samples=false",
            "--installation_map_url=https://installationmap.netlify.app/",
            "--app.name=eks-sclc",
            "--filter_groups_by_appname=false",
            # connecting over dbcp
            "--dbconnector=dbcp",
            "--authenticate=saml",
            "--authorization=false",
            "--db.user=$(DB_USER)",
            "--db.password=$(DB_PASSWORD)",
            "--db.suppress_schema_version_mismatch_errors=true",
            "--spring.datasource.driver-class-name=com.mysql.jdbc.Driver",
            "--spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect",
            "--spring.datasource.url=jdbc:mysql://$(DB_HOST):3306/$(DB_PORTAL_DB_NAME)?zeroDateTimeBehavior=convertToNull&useSSL=false",
            "--spring.datasource.username=$(DB_USER)",
            "--spring.datasource.password=$(DB_PASSWORD)",
          #"--tomcat.catalina.scope=runtime",
            "--enable_cross_study_expression=(studies)=>studies.filter(s=>/pan_can_atlas/.test(s.studyId) === false).length === 0",
            "--show.transcript_dropdown=true",
            "--skin.show_tweet_button=$(SKIN_SHOW_TWEET_BUTTON)",
            "--skin.email_contact=cdsi@mskcc.org",
            "--skin.data_sets_footer=Data sets of published studies were curated from literature. Data sets of legacy TCGA studies were downloaded from the <a href=\"http://gdac.broadinstitute.org\">Broad Institute Firehose</a>, last updated 1/28/2016.",
            "--skin.data_sets_header=The table below lists the number of available samples per cancer study and data type.",
            "--skin.authorization_message=Welcome to cBioPortal. Logging in will allow you to access your studies and groups from any computer, and cBioPortal will also remember your study view charts preferences for each study (i.e. order of the charts, type of charts and visibility). Login is optional and not required to access any of the other features of cBioPortal.",
            "--skin.blurb=",
            "--show.mdacc.heatmap=true",
            "--session.service.url=https://session-service.cbioportal.org/api/sessions/sclc_portal/",
            "--session.service.origin=*",
            "--session.service.user=$(SESSION_SERVICE_USER_NAME)",
            "--session.service.password=$(SESSION_SERVICE_USER_PASSWORD)",
            "--google_analytics_profile_id=$(GOOGLE_ANALYTICS_PROFILE_ID)",
            "--googleplus.consumer.key=$(GOOGLE_PLUS_CONSUMER_KEY)",
            "--googleplus.consumer.secret=$(GOOGLE_PLUS_CONSUMER_SECRET)",
            "--microsoftlive.consumer.key=$(MICROSOFT_LIVE_CONSUMER_KEY)",
            "--microsoftlive.consumer.secret=$(MICROSOFT_LIVE_CONSUMER_SECRET)",
            "--bitly.url=$(BITLY_URL)",
            "--bitly.access.token=$(BITLY_ACCESS_TOKEN)",
            "--sentry.dsn=$(SENTRY_DSN)",
            "--sentry.factory=org.cbioportal.logging.SentryClientFactory",
            #"--sentryjs.frontend_project_endpoint=$(SENTRY_FRONTEND_DSN)",
            "--sitemaps=false",
            "--oncokb.public_api.url=https://core.oncokb.aws.mskcc.org/api/v1",
            # token is not needed to access MSK OncoKB instance
            "--oncokb.token=fake_token",
            "--oncokb.merge_icons_by_default=false",
            "--genomenexus.url=https://v1.genomenexus.org",
            "--show.genomenexus.annotation_sources=mutation_assessor",
            "--matchminer.url=http://ec2-54-158-52-176.compute-1.amazonaws.com:5555",
            "--matchminer.token=$(MATCHMINER_TOKEN)",
            # redis session store settings (different from redis persistence cache)
            "--spring.session.store-type=redis",
            "--spring.data.redis.host=$(REDIS_SESSION_HOST)",
            "--spring.data.redis.port=$(REDIS_SESSION_PORT)",
            "--spring.data.redis.password=$(REDIS_SESSION_PASSWORD)",
            # To enable redis session store, we need to set
            # spring.autoconfigure.exclude to a random value to override the
            # property in applications.properties.EXAMPLE
            "--spring.autoconfigure.exclude=dontexcludeanythingplz",
            # cache settings (currently redis)
#            "--cache.statistics_endpoint_enabled=false",
            "--redis.database=2",
            "--persistence.cache_type=redis",
            "--redis.leader_address=redis://cbioportal-persistence-redis-master:6379",
            "--redis.follower_address=redis://cbioportal-persistence-redis-replicas:6379",
            "--redis.password=$(REDIS_PASSWORD)",
            "--ehcache.cache_type=none",
            "--cache.endpoint.api-key=$(CACHE_API_KEY)",
            "--cache.endpoint.enabled=true",
            "--redis.clear_on_startup=false",
            # misc frontend settings (this is NOT for backend persistence layer caching)
            "--enable_persistent_cache=false",
            # auth
            "--security.cors.allowed-origins=*",
            # "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.assertingparty.metadata-uri=/cbioportal/msk-beta-cbioportal-saml-idp-metadata.xml",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.assertingparty.metadata-uri=https://keycloak.cbioportal.mskcc.org/auth/realms/external/protocol/saml/descriptor",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.entity-id=sclc-v6",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.signing.credentials[0].certificate-location=file:/cbioportal/local.crt",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.signing.credentials[0].private-key-location=file:/cbioportal/local.key",
            # "--logging.level.org.springframework.security=DEBUG",
            # "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.singlelogout.binding=POST",
            # "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.singlelogout.response-url=http://localhost:8080/logout/saml2/slo",
            # compress on client side
            "--enable_request_body_gzip_compression=true",
            "--server.compression.enabled=true",
            "--server.tomcat.connection-timeout=20000",
            "--server.tomcat.max-http-response-header-size=16384",
            "--server.max-http-request-header-size=16384",
            "--server.port=8888",
        ]
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8888
          initialDelaySeconds: 45
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 15
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8888
          initialDelaySeconds: 180
          timeoutSeconds: 2
          periodSeconds: 12
          failureThreshold: 20
        name: eks-sclc
        ports:
        - containerPort: 8888
          protocol: TCP
        - containerPort: 8849
          protocol: TCP
        resources:
          requests:
              memory: 2Gi
          limits:
              memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: small-memory-portals
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: eks-sclc
  name: eks-sclc
  selfLink: /api/v1/namespaces/default/services/eks-sclc
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    run: eks-sclc
  type: ClusterIP
