apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: gn-vep-grch37
  name: gn-vep-grch37
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gn-vep-grch37
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gn-vep-grch37
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8888"
        - name: VERBOSE
          value: "true"
        - name: VEP_ASSEMBLY
          value: "GRCh37"
        image: genomenexus/genome-nexus-vep:v0.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: vep-data
          mountPath: /opt/vep/.vep
        readinessProbe:
          httpGet:
            path: /vep/human/region/7:140453136-140453136:1/T
            port: 8888
          initialDelaySeconds: 10
          timeoutSeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /vep/human/region/7:140453136-140453136:1/T
            port: 8888
          initialDelaySeconds: 31
          timeoutSeconds: 60
          periodSeconds: 30
        name: gn-vep-grch37
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 3Gi
          limits:
            cpu: 2
            memory: 9Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # download data from s3 bucket (takes ~15m).
      # TODO: It might be better to create a volume from an existing snapshot.
      initContainers:
      - name: download-vep-cache
        image: busybox:1.30.0
        command: ['sh', '-c',
            'echo "Starting..."; cd /vep_data; mkdir -p tmp; chmod a+w tmp; wget https://oncokb.s3.amazonaws.com/gn-vep-data/98_GRCh37/98_GRCh37.tar -O 98_GRCh37.tar; tar xvf 98_GRCh37.tar; echo $?; echo "Ending...";'
        ]
        volumeMounts:
        - name: vep-data
          mountPath: /vep_data
      volumes:
      - name: vep-data
        persistentVolumeClaim:
          claimName: gn-vep-pvc-grch37
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: gn-vep-grch37
    app: gn-vep-grch37
  name: gn-vep-grch37
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  - port: 443
    name: https
    targetPort: 8888
  selector:
    run: gn-vep-grch37
  type: ClusterIP
