#!/bin/bash
set -a # causes all functions/vars defined in this file to be exported to subshells

AIRFLOW_DEP=/home/chennac/airflow-deployment

function afctl() {
    kubectl -n airflow "$@"
}

function scheduler-pod() {
    afctl get pod | cut -d' ' -f1 | grep airflow-scheduler | head -n1
}

function webserver-pod() {
    afctl get pod | cut -d' ' -f1 | grep airflow-webserver | head -n1
}

function worker-pods() {
    afctl get pod | cut -d' ' -f1 | grep nci-crdc-dag
}

function scheduler-logs() {
    afctl logs $(scheduler-pod) -f -c scheduler
}

function delete-airflow-chart() {
    helm delete airflow --namespace airflow
}

function delete-airflow-pvcs() {
    # Delete all Airflow PVCs except for efs-pv-claim
    # note: this must be run before deleting the PVs
    pvcs_to_delete=(
        data-airflow-postgresql-0
        logs-airflow-triggerer-0
        logs-airflow-worker-0
        redis-db-airflow-redis-0
        airflow-logs
    )
    for pvc in "${pvcs_to_delete[@]}"; do
        # Force immediate deletion
        kubectl patch pvc $pvc -n airflow -p '{"metadata":{"finalizers":null}}'
        timeout 5 kubectl -n airflow delete pvc $pvc --grace-period=0 --force
    done

    afctl get pvc
}

function delete-airflow-pvs() {
    # Delete all Airflow PVs except for efs-pv
    pvs_to_delete=$(kubectl get pv | grep airflow | grep -v efs-pv | grep -v airflow-logs | cut -d' ' -f1)
    for pv in "${pvs_to_delete[@]}"; do
        # Force immediate deletion
        kubectl patch pv $pv -n airflow -p '{"metadata":{"finalizers":null}}'
        timeout 5 kubectl -n airflow delete pv $pv --grace-period=0 --force
    done

    afctl get pv
}

function delete-airflow-workers() {
    # Clean up worker pods
    worker_pods=$(worker-pods)
    for pod in "${worker_pods[@]}"; do
        timeout 5 kubectl -n airflow delete pod $pod
    done

    afctl get pod
}

function install-airflow-chart() {
    helm install -f $AIRFLOW_DEP/values.yaml -f $AIRFLOW_DEP/override-values.yaml airflow apache-airflow/airflow --namespace airflow --debug --timeout 10m
}

function reboot-airflow-server() {
    delete-airflow-chart
    delete-airflow-pvcs
    delete-airflow-pvs
    delete-airflow-workers
    install-airflow-chart
}

function ssh-into-pod() {
    afctl exec -it $1 -- /bin/bash
}

# TODO pushing new Docker images
