apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oncokb-main
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/175678591974/clusters/oncokb-research/apps/oncokb-main
      targetRevision: HEAD
      directory:
        recurse: true
      ref: k8s-repo
    - repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 20.8.0
      chart: redis
      helm:
        releaseName: public-session-redis
        valueFiles:
          - $k8s-repo/argocd/aws/175678591974/clusters/oncokb-research/apps/oncokb-main/oncokb_public_session_redis_values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
