apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-classes
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/175678591974/clusters/oncokb-research/apps/storage-classes
      targetRevision: HEAD
      directory:
        recurse: true
      ref: cert-manager
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
