apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: uablock-browser
  namespace: default
spec:
  plugin:
    uablock:
      regex:
        - ".*Mozilla.*"
      statusCode: 403
      responseMessage: "For browser usage, visit cbioportal.org"