apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentic-cancer-gene-classification
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::175678591974:role/userServiceRoleAcgcBedrock
