apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: default
data:
  6379: "default/cbioportal-public-persistence-redis-dev-master:6379"
  6380: "default/cbioportal-public-persistence-redis-dev-replicas:6379"