apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-aws-creds-manager-pod-restarter
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::203403084713:role/userServiceRoleK8sAwsCredsManager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-aws-creds-manager-pod-restarter-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-aws-creds-manager-pod-restarter-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: k8s-aws-creds-manager-pod-restarter
    namespace: default
roleRef:
  kind: Role
  name: k8s-aws-creds-manager-pod-restarter-role
  apiGroup: rbac.authorization.k8s.io