apiVersion: v1
kind: PersistentVolume
metadata:
  name: cbioportal-session-service-mongodb-dev
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: vol-0ee3fafcdfa7bee78
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbioportal-session-service-mongodb-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: cbioportal-session-service-mongodb-dev