apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncokb-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oncokb-public
      version: 'v1'
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oncokb-public
        version: 'v1'
    spec:
      containers:
        - name: oncokb-public
          image: oncokb/oncokb-public:3.9.0-alpha.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod,no-liquibase
            - name: APPLICATION_REDIS_TYPE
              value: '$(REDIS_TYPE)'
            - name: APPLICATION_REDIS_ADDRESS
              value: '$(REDIS_ADDRESS)'
            - name: APPLICATION_REDIS_PASSWORD
              value: '$(REDIS_PASSWORD)'
            - name: APPLICATION_REDIS_EXPIRATION
              value: '$(REDIS_EXPIRATION)'
            - name: APPLICATION_DB_READ_ONLY
              value: 'false'
            - name: JAVA_OPTS
              value: '-Xmx1024m -Xms512m'
            - name: SENTRY_EXCEPTION_RESOLVER_ORDER
              value: '-2147483647'
            - name: SENTRY_TRACES_SAMPLE_RATE
              value: '.2'
            - name: SPRING_DATASOURCE_URL
              value: '${DB_URL}/oncokb_public'
            - name: SPRING_DATASOURCE_USERNAME
              value: '${DB_USERNAME}'
            - name: SPRING_DATASOURCE_PASSWORD
              value: '${DB_PASSWORD}'
          envFrom:
            - configMapRef:
                name: oncokb-public
            - configMapRef:
                name: oncokb-redis-cluster
            - configMapRef:
                name: oncokb-db-msk-dev-rds
          readinessProbe:
            httpGet:
              path: /
              port: 9095
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 9095
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 750m
          ports:
            - name: http
              containerPort: 9095
          volumeMounts:
            # The subPath is needed so that mounting the secret as a single file doesn't override
            # the contents of the existing directory.
            - mountPath: /app/resources/config/recaptcha/oncokb-recaptcha-credentials.json
              subPath: oncokb-recaptcha-credentials.json
              name: recaptcha-credentials
      volumes:
      - name: recaptcha-credentials
        secret:
          secretName: oncokb-recaptcha-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: oncokb-public
  labels:
    app: oncokb-public
spec:
  selector:
    app: oncokb-public
  type: ClusterIP
  ports:
    - port: 9095
