apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/397229547211/clusters/cbioportal-dev/apps/ingress
      targetRevision: HEAD
      directory:
        recurse: true
      ref: k8s-repo
    - repoURL: https://github.com/knowledgesystems/portal-configuration.git
      path: argocd/aws/397229547211/clusters/cbioportal-dev/secrets/ingress
      targetRevision: HEAD
      directory:
        recurse: true
      ref: portal-configuration-repo
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.12.1
      chart: ingress-nginx
      helm:
        releaseName: fluffy-kitty
        valueFiles:
          - $k8s-repo/argocd/aws/397229547211/clusters/cbioportal-dev/apps/ingress/values.yaml
          - $portal-configuration-repo/argocd/aws/397229547211/clusters/cbioportal-dev/secrets/ingress/cert.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
