apiVersion: v1
kind: Service
metadata:
  name: cbiolab-postgres
spec:
  selector:
    app: cbiolab-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  type: ClusterIP
