prometheus:
  additionalServiceMonitors:
    - name: oncokb-eu-ingress-nginx-service-monitor
      jobLabel: oncokb-eu-ingress-nginx
      selector:
        matchLabels:
          app.kubernetes.io/instance: oncokb-eu-ingress-nginx
          app.kubernetes.io/name: ingress-nginx
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: metrics
          interval: 30s
  prometheusSpec:
    retention: 10d
    # aws specific storage class
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: gp2
          resources:
            requests:
              storage: 40Gi
alertmanager:
  enabled: false
grafana:
  enabled: false