apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak